### ISSUE TITLE
Duniter Desktop does not work stable on Wayland

### ISSUE THREAD

**Issue by RavanH** [duniter/duniter#1000]
Starting Duniter Desktop on Gnome with Wayland does not always work well. Sometimes Duniter starts fine (even if the first app window takes a long time to be created) but other times it just seems to remain stuck loading with a blank window.

Will provide some log excerpts later...

**Comment by RavanH** [comment]
Starting from command line while on Wayland:

    $ duniter-desktop
    [30403:30424:0603/205528:ERROR:nss_util.cc(809)] After loading Root Certs, loaded==false: NSS error code: -8018
    2017-06-03T20:55:58+02:00 - debug: Plugging file system...
    2017-06-03T20:56:00+02:00 - debug: Loading conf...
    2017-06-03T20:56:00+02:00 - debug: Configuration saved.
    2017-06-03T20:56:00+02:00 - debug: Opening SQLite database "/home/ravanhagen/.config/duniter/duniter_default/duniter.db"...
    2017-06-03T20:56:01+02:00 - debug: Upgrade database...
    2017-06-03T20:56:01+02:00 - info: Web administration accessible at following address: http://localhost:9220
    2017-06-03T20:56:02+02:00 - info: Duniter server listening on http://192.168.1.101:9998
    2017-06-03T20:56:02+02:00 - error: Error on WS Server
    2017-06-03T20:56:02+02:00 - error:  Error: listen EINVAL fe80::13e:c274:c1bb:d36f:9998
        at Object.exports._errnoException (util.js:1036:11)
        at exports._exceptionWithHostPort (util.js:1059:20)
        at Server._listen2 (net.js:1239:19)
        at listen (net.js:1288:10)
        at net.js:1398:9
        at _combinedTickCallback (internal/process/next_tick.js:77:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
    2017-06-03T20:56:02+02:00 - warn: Could NOT listen to http://fe80::13e:c274:c1bb:d36f:9998
    2017-06-03T20:56:02+02:00 - warn:  Error: listen EINVAL fe80::13e:c274:c1bb:d36f:9998
        at Object.exports._errnoException (util.js:1036:11)
        at exports._exceptionWithHostPort (util.js:1059:20)
        at Server._listen2 (net.js:1239:19)
        at listen (net.js:1288:10)
        at net.js:1398:9
        at _combinedTickCallback (internal/process/next_tick.js:77:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
    2017-06-03T20:56:02+02:00 - info: UPnP: configuring...
    2017-06-03T20:56:02+02:00 - trace: UPnP: mapping external port 9998 to local 9998...
    2017-06-03T20:56:02+02:00 - error: 
    Afgebroken (geheugendump gemaakt)

**Comment by RavanH** [comment]
Starting a second time from command line shows the same startup messages except that last empty error, but the duniter window remains blank after the first splash image (logo) disappeared, even though the usual messages about connecting to peers and fetching blocks are running in the terminal window.

Then starting a third time, the window gui loads just fine...

**Comment by c-geek** [comment]
So I don't think Wayland is involved in this issue, but rather #997.

**Comment by RavanH** [comment]
OK just coïncidence then. Closing this issue...
