### ISSUE TITLE
Install fail with YunoHost package

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#1004]
```bash
+ deb=/tmp/duniter-server-v1.3.8-linux-armv7l.deb
+ sudo dpkg -i /tmp/duniter-server-v1.3.8-linux-armv7l.deb
+ sudo rm -f /tmp/duniter-server-v1.3.8-linux-armv7l.deb
+ sudo duniter config --ipv4 127.0.0.1 --port 10901 --remoteh duniter.moul.re --remotep 80 --noupnp
Warnung: 2017-06-14T10:10:58+02:00 - debug: Plugging file system...
Warnung: 2017-06-14T10:10:58+02:00 - debug: Loading conf...
Warnung: 2017-06-14T10:10:59+02:00 - error:  SyntaxError: Unexpected token . in JSON at position 682
Warnung:     at Object.parse (native)
Warnung:     at /opt/duniter/app/lib/cfs.js:196:19
Warnung:     at next (native)
Warnung:     at onFulfilled (/opt/duniter/node_modules/co/index.js:65:19)
Warnung:     at process._tickCallback (internal/process/next_tick.js:109:7)
Skript '/var/cache/yunohost/from_file/scripts/remove' wird ausgeührt...
+ set -u
```
I don't know at which step this problem occur.
I couldn't reproduced it trying two lines for configuration and sync processes manually.
I don't seems to come from configuration file, as I tried to remove all data before installing.
Do you have an idea?

**Comment by c-geek** [comment]
You should try to remove `~/.config/duniter` folder.

**Comment by M5oul** [comment]
Ok, fixed. I confuse my servers. Thanks.
