### ISSUE TITLE
Many logs about peers in db

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#1038]
Testing #1037 TypeScript branch `ts` at https://github.com/duniter/duniter/commit/20e89508688918378a8f663e1826daef8e0e4536 commit, there is many logs concerning peers add/removed?
Here is an extract:
```bash
2017-07-19T10:44:22+02:00 - info: Peer CRBxCJrTA6tmHsgt9cQh9SHcCc8w8q95YTp38CPHx2Uk unreachable: now considered as DOWN.
2017-07-19T10:44:22+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: ✔ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: POST Peer FEkbc4BfJu#36527
2017-07-19T10:44:22+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:22+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ⬇ PEER FEkbc4Bf
2017-07-19T10:44:23+02:00 - info: ✘ PEER FEkbc4Bf
2017-07-19T10:44:30+02:00 - info: ⬇ PEER Ds1z6Wd8
```

- [More logs](https://moul.re/zerobin/?23431f1e37074452#rRw7FCdzJ600WJi1osnkQLEMGFmNbTU03Na3ngqt3gI=)

**Comment by M5oul** [comment]
With recent commits pushed, I have logs saying there is issues to reach other nodes:
```bash
2017-07-20T12:30:27+02:00 - info: POST Peer D9D2zaJoWY#36866
2017-07-20T12:30:27+02:00 - info: ✔ PEER D9D2zaJo
2017-07-20T12:30:27+02:00 - info: Matched 4 zeros 000069F850DA382363D0A8BCA1AD7F708AC4BF57841DFADE25CA6F2C35D066BA with Nonce = 10400000004281 for block#36867 by GfKERH
2017-07-20T12:30:27+02:00 - info: POST Peer D9D2zaJoWY#36866
2017-07-20T12:30:27+02:00 - warn: Could not reach g2.elois.org:10901
2017-07-20T12:30:27+02:00 - warn: Could not reach g1.elois.org:80
2017-07-20T12:30:27+02:00 - warn: Could not reach 82.239.120.237:10901
2017-07-20T12:30:27+02:00 - warn: Could not reach g1.duniter.inso.ovh:80
2017-07-20T12:30:27+02:00 - warn: Could not reach duniter.floth.fr:80
2017-07-20T12:30:27+02:00 - warn: Could not reach arm.moul.re:63547
2017-07-20T12:30:27+02:00 - warn: Could not reach duniter.silibre.com:80
2017-07-20T12:30:27+02:00 - warn: Could not reach duniter.kamsoft.fr:80
2017-07-20T12:30:27+02:00 - warn: Could not reach g1.monnaielibreoccitanie.org:443
2017-07-20T12:30:27+02:00 - warn: Could not reach www.jouin.xyz:10901
2017-07-20T12:30:27+02:00 - warn: Could not reach duniter.vincentuc.fr:80
2017-07-20T12:30:28+02:00 - info: Matched 3 zeros 000998EB631A1685566E468F6A37A349FAA7F7059E8B75B7E01DA2884B916E99 with Nonce = 10300000003648 for block#36867 by GfKERH
2017-07-20T12:30:33+02:00 - info: Matched 3 zeros 000A0084A030F3F4615993603C3DBC35A100362F2CA1D49B173FA1D0180815C3 with Nonce = 10200000004388 for block#36867 by GfKERH
2017-07-20T12:30:37+02:00 - warn: ESOCKETTIMEDOUT
```

**Comment by M5oul** [comment]
Other kind of logs concerning same issue:
```bash
2017-08-04T13:42:13+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-08-04T13:42:13+02:00 - info: ⬇ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - warn: Could not reach duniter.floth.fr:80
2017-08-04T13:42:13+02:00 - info: ⬇ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-08-04T13:42:13+02:00 - info: ⬇ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-08-04T13:42:13+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-08-04T13:42:13+02:00 - info: ⬇ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-08-04T13:42:13+02:00 - warn: Could not reach duniter.kamsoft.fr:80
2017-08-04T13:42:13+02:00 - info: ⬇ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-08-04T13:42:13+02:00 - warn: Could not reach g1.smyds.net:443
2017-08-04T13:42:13+02:00 - info: ⬇ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:13+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-08-04T13:42:13+02:00 - warn: Could not reach 78.251.5.57:61650
2017-08-04T13:42:13+02:00 - warn: Could not reach 88.162.240.60:57586
2017-08-04T13:42:13+02:00 - warn: Could not reach duniter.qbuissondebon.info:8999
2017-08-04T13:42:14+02:00 - info: ⬇ PEER Be1eVp7e
2017-08-04T13:42:14+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:14+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-08-04T13:42:14+02:00 - info: ⬇ PEER Be1eVp7e
2017-08-04T13:42:14+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:14+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-08-04T13:42:14+02:00 - info: ⬇ PEER Be1eVp7e
2017-08-04T13:42:14+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:14+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-08-04T13:42:14+02:00 - info: ⬇ PEER Be1eVp7e
2017-08-04T13:42:14+02:00 - info: ✘ PEER Be1eVp7e
2017-08-04T13:42:14+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
```

**Comment by c-geek** [comment]
Please open another issue for a different problem, it may not be linked.

**Comment by M5oul** [comment]
Since this commit I can't reach my node.
Here is logs:
```bash
2017-08-06T16:15:54+02:00 - info: Pulling blocks from the network...
2017-08-06T16:15:54+02:00 - info: Duniter server listening on http://192.168.1.21:10901
2017-08-06T16:15:54+02:00 - error: Error on WS Server
2017-08-06T16:15:54+02:00 - error:  Error: listen EADDRNOTAVAIL 2a01:e34:ee36:b2d0:1879:97c5:5f21:728b:10901
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1245:19)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
2017-08-06T16:15:54+02:00 - warn: Could NOT listen to http://2a01:e34:ee36:b2d0:1879:97c5:5f21:728b:10901
2017-08-06T16:15:54+02:00 - warn:  Error: listen EADDRNOTAVAIL 2a01:e34:ee36:b2d0:1879:97c5:5f21:728b:10901
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1245:19)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
2017-08-06T16:15:54+02:00 - info: Sibling endpoints: 0=BASIC_MERKLED_API arm.moul.re 78.227.107.45 2a01:e34:ee36:b2d0:11:1ff:fec1:e6c4 63547, 1=DEFAULT_ENDPOINT
2017-08-06T16:15:55+02:00 - info: External access: desktop.moul.re:10901
2017-08-06T16:15:55+02:00 - info: ⬇ PEER GfKERHnJ
2017-08-06T16:15:55+02:00 - info: ✘ PEER GfKERHnJ
```

**Comment by c-geek** [comment]
Your IPv6 configuration does not match your machine's IPv6.
