### ISSUE TITLE
Duniter Desktop starts looping for no reason on "The proof-of-work generation was canceled: [object Object]"

### ISSUE THREAD

**Issue by jytou** [duniter/duniter#1096]
For the second time in 3 days, my duniter desktop started looping on the following in the logs:
```
2017-09-10T19:09:25+02:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-09-10T19:09:25+02:00 - trace: PoW loops = 143672
2017-09-10T19:09:25+02:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-09-10T19:09:25+02:00 - trace: PoW loops = 143673
2017-09-10T19:09:25+02:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-09-10T19:09:25+02:00 - trace: PoW loops = 143674
2017-09-10T19:09:25+02:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-09-10T19:09:25+02:00 - trace: PoW loops = 143675
```
It gets stuck on an old block and doesn't go forward or calculate anything anymore.

When I try to restart it, it gives the following error:
```
2017-09-10T19:13:14+02:00 - error:  TypeError: Cannot read property 'transactions' of null
    at DuniterBlockchain.<anonymous> (/opt/duniter/app/lib/blockchain/DuniterBlockchain.js:443:36)
    at next (<anonymous>)
    at /opt/duniter/app/lib/blockchain/DuniterBlockchain.js:7:71
    at __awaiter (/opt/duniter/app/lib/blockchain/DuniterBlockchain.js:3:12)
    at DuniterBlockchain.undoDeleteTransactions (/opt/duniter/app/lib/blockchain/DuniterBlockchain.js:442:16)
    at DuniterBlockchain.<anonymous> (/opt/duniter/app/lib/blockchain/DuniterBlockchain.js:406:24)
    at next (<anonymous>)
    at fulfilled (/opt/duniter/app/lib/blockchain/DuniterBlockchain.js:4:58)
```

And when I restart it again, I get a core dumped. Last time, it did restart correctly and after a sync it was back on track. Not this time. It took 4 restarts until it got back on track and it is now on the latest block.

**Comment by M5oul** [comment]
It seems I had this issue previously.

**Comment by c-geek** [comment]
About the `warn: The proof-of-work generation was canceled: [object Object]`, please see #1098.

For the `error:  TypeError: Cannot read property 'transactions' of null`, I know that this error occurs when Duniter is being closed / restarted while being recording a block / resolving a fork. So I will try to put some safeguards on it.

**Comment by c-geek** [comment]
Now when the server disconnects (for example because of a Ctrl+C), it will wait to end the current task in the documents FIFO, the big FIFO that Duniter uses to add documents (Blocks, Transactions, Certifications, ...).
