### ISSUE TITLE
Node stop running

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#1097]
On branch `dev` and commit `004d8ba41279b8173ae117180d841903ef8c484d`:
```bash
2017-09-10T19:52:29+02:00 - info: ⬇ PEER GfKERHnJ
2017-09-10T19:52:29+02:00 - info: ✘ PEER GfKERHnJ
2017-09-10T19:52:29+02:00 - error:  httpCode=400, ucode=2023, message=Peer document already known
2017-09-10T19:52:29+02:00 - warn: Could not reach duniter.jowe.fr:443
2017-09-10T19:52:30+02:00 - error:  TypeError: Cannot read property 'toString' of undefined
    at Parser.exports.Parser.Parser.parseString (/home/moul/projects/duniter/node_modules/xml2js/lib/xml2js.js:206:14)
    at Parser.parseString (/home/moul/projects/duniter/node_modules/xml2js/lib/xml2js.js:6:61)
    at Request._callback (/home/moul/projects/duniter/node_modules/nnupnp/lib/nat-upnp/device.js:149:14)
    at Request.self.callback (/home/moul/projects/duniter/node_modules/nnupnp/node_modules/request/main.js:120:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/moul/projects/duniter/node_modules/nnupnp/node_modules/request/main.js:633:16)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/moul/projects/duniter/node_modules/nnupnp/node_modules/request/main.js:595:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by c-geek** [comment]
I guess you did not have UPnP available on your network.

Fixed by 11a1b0277d2986be73ccc06872f6ed797ff08f33.
