### ISSUE TITLE
First sync fail

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#1125]
With v1.6.6, YunoHost package and 64bits arch, first sync fail:
```bash
2017-09-27T15:00:18+00:00 - error:  Error: connect ECONNREFUSED 83.115.9.217:10902
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
2017-09-27T15:00:18+00:00 - info: Getting chunck #202/224 from 50500 to 50749 on peer duniter.s-entraider.net:10901
2017-09-27T15:00:18+00:00 - info: GOT chunck #204/224 from 51000 to 51249 on peer 185.167.16.19:10901
2017-09-27T15:00:18+00:00 - info: AUGMENTED DOWNLOAD SLOTS! Now has 8 slots
2017-09-27T15:00:18+00:00 - info: Downloaded 8%, Applied 0%
2017-09-27T15:00:18+00:00 - info: Getting chunck #201/224 from 50250 to 50499 on peer duniter.adn.life:10901
2017-09-27T15:00:18+00:00 - info: Getting chunck #200/224 from 50000 to 50249 on peer g1.duniter.org:10901
2017-09-27T15:00:18+00:00 - info: GOT chunck #202/224 from 50500 to 50749 on peer duniter.s-entraider.net:10901
2017-09-27T15:00:18+00:00 - info: Deceleration = -0.8215361445783133 (118.5/664), AddedNodePercent = 0.125
2017-09-27T15:00:18+00:00 - info: Getting chunck #199/224 from 49750 to 49999 on peer duniter.s-entraider.net:10901
2017-09-27T15:00:18+00:00 - info: GOT chunck #199/224 from 49750 to 49999 on peer duniter.s-entraider.net:10901
2017-09-27T15:00:18+00:00 - info: AUGMENTED DOWNLOAD SLOTS! Now has 9 slots
2017-09-27T15:00:18+00:00 - info: Getting chunck #198/224 from 49500 to 49749 on peer duniter.s-entraider.net:10901
2017-09-27T15:00:19+00:00 - info: Getting chunck #197/224 from 49250 to 49499 on peer duniter.help-web-low.fr:8999
2017-09-27T15:00:19+00:00 - info: GOT chunck #200/224 from 50000 to 50249 on peer g1.duniter.org:10901
2017-09-27T15:00:19+00:00 - info: Deceleration = 0.6390101892285298 (187.66666666666666/114.5), AddedNodePercent = 0.1111111111111111
2017-09-27T15:00:19+00:00 - info: REDUCED DOWNLOAD SLOT! Now has 8 slots
2017-09-27T15:00:19+00:00 - info: Downloaded 9%, Applied 0%
2017-09-27T15:00:19+00:00 - info: GOT chunck #198/224 from 49500 to 49749 on peer duniter.s-entraider.net:10901
2017-09-27T15:00:19+00:00 - info: AUGMENTED DOWNLOAD SLOTS! Now has 9 slots
```
The node is not running after that.

Tried a second time:
```bash
2017-09-27T15:07:29+00:00 - info: AUGMENTED DOWNLOAD SLOTS! Now has 2 slots
2017-09-27T15:07:29+00:00 - warn: Chunk #224 is COMPLETE from duniter.aquilenet.fr:10901
2017-09-27T15:07:29+00:00 - warn: Chunk #223 is COMPLETE from filesystem:blockchain
2017-09-27T15:07:29+00:00 - info: Downloaded 1%, Applied 0%
2017-09-27T15:07:29+00:00 - warn: Chunk #222 is COMPLETE from filesystem:blockchain
2017-09-27T15:07:29+00:00 - warn: Chunk #221 is COMPLETE from filesystem:blockchain
2017-09-27T15:07:29+00:00 - info: Downloaded 2%, Applied 0%
2017-09-27T15:07:29+00:00 - warn: Chunk #220 is COMPLETE from filesystem:blockchain
2017-09-27T15:07:30+00:00 - warn: Chunk #219 is COMPLETE from filesystem:blockchain
2017-09-27T15:07:30+00:00 - info: Downloaded 3%, Applied 0%
2017-09-27T15:07:30+00:00 - warn: Chunk #218 is COMPLETE from filesystem:blockchain
2017-09-27T15:07:30+00:00 - warn: Chunk #217 is COMPLETE from filesystem:blockchain
2017-09-27T15:07:30+00:00 - info: Downloaded 4%, Applied 0%
2017-09-27T15:07:30+00:00 - warn: Chunk #216 is COMPLETE from filesystem:blockchain
2017-09-27T15:07:30+00:00 - info: Getting chunck #215/224 from 53750 to 53999 on peer remuniter.cgeek.fr:16120
2017-09-27T15:07:30+00:00 - info: Getting chunck #214/224 from 53500 to 53749 on peer duniter.floth.fr:80
2017-09-27T15:07:30+00:00 - info: GOT chunck #214/224 from 53500 to 53749 on peer duniter.floth.fr:80
2017-09-27T15:07:30+00:00 - info: Deceleration = 1.4570135746606336 (543/221), AddedNodePercent = 0.5
2017-09-27T15:07:30+00:00 - info: REDUCED DOWNLOAD SLOT! Now has 1 slots
2017-09-27T15:07:35+00:00 - info: GOT chunck #215/224 from 53750 to 53999 on peer remuniter.cgeek.fr:16120
2017-09-27T15:07:35+00:00 - info: AUGMENTED DOWNLOAD SLOTS! Now has 2 slots
2017-09-27T15:07:35+00:00 - warn: Chunk #215 is COMPLETE from remuniter.cgeek.fr:16120
2017-09-27T15:07:37+00:00 - warn: Chunk #214 is COMPLETE from duniter.floth.fr:80
2017-09-27T15:07:38+00:00 - info: Downloaded 5%, Applied 0%
2017-09-27T15:07:39+00:00 - info: Getting chunck #213/224 from 53250 to 53499 on peer duniter.qbuissondebon.info:8999
^Croot@moul:~# duniter status
Duniter is not running.
```

**Comment by M5oul** [comment]
Linked to https://github.com/YunoHost-Apps/duniter_ynh/issues/15.

**Comment by M5oul** [comment]
So, to resume.
Duniter initial sync needs more than 512MB free memory to works.
That's, of course, an important issue.
Current solution, is to copy `wotb.bin` and `duniter.db` from an other node.

**Comment by M5oul** [comment]
I tried to resize the server to 1GB. Sync works fine.
Then, I decided to resize back to 512MB with current synced node.
Unfortunately, running the node with other YunoHost components worked like 30min then have been killed due to OOM.
May be something could be done on that side.
Or, we could recommend using at least 1GB memory to run a computing node on Ğ1 currency.

**Comment by M5oul** [comment]
Ok, I found a responsible.
I thinks a node could works on a 512MB server.
The responsible is `duniter logs`!
![duniter_logs_ram_res](https://user-images.githubusercontent.com/4758871/30973770-4154a776-a46e-11e7-92aa-4a0c7eaf6060.png)

**Comment by M5oul** [comment]
Ok, there are two distinct issues here.
I move the one concerning logs here: https://github.com/duniter/duniter/issues/1127.

**Comment by M5oul** [comment]
OOM kill process without `duniter logs` on a 512GB.
I am trying with BMA disabled as requests could lead to memory pick usage.

**Comment by M5oul** [comment]
The node stops at this step:
```bash
2017-09-29T16:18:34+00:00 - warn:  httpCode=400, ucode=1015, message=Document already under treatment
2017-09-29T16:18:34+00:00 - info: ⬇ PEER ECTQrRoR
2017-09-29T16:18:34+00:00 - warn:  httpCode=400, ucode=1015, message=Document already under treatment
2017-09-29T16:18:34+00:00 - info: WS2P: Could not connect to peer -------- using `WS2P 83.115.9.217 20925: WS2P connection timeout`
2017-09-29T16:18:34+00:00 - error: Unhandled rejection: WS2P connection timeout
2017-09-29T16:18:34+00:00 - error: WS2P connection timeout
2017-09-29T16:18:34+00:00 - info: ✔ PEER ECTQrRoR
2017-09-29T16:18:34+00:00 - info: ⬇ PEER ECTQrRoR
2017-09-29T16:18:34+00:00 - info: ⬇ PEER ECTQrRoR
2017-09-29T16:18:34+00:00 - warn:  httpCode=400, ucode=1015, message=Document already under treatment
2017-09-29T16:18:34+00:00 - info: ⬇ PEER ECTQrRoR
2017-09-29T16:18:34+00:00 - warn:  httpCode=400, ucode=1015, message=Document already under treatment
2017-09-29T16:18:34+00:00 - info: ⬇ PEER ECTQrRoR
2017-09-29T16:18:34+00:00 - warn:  httpCode=400, ucode=1015, message=Document already under treatment
2017-09-29T16:18:34+00:00 - info: WS2P: Could not connect to peer -------- using `WS2P 83.115.9.217 20925: WS2P connection timeout`
2017-09-29T16:18:34+00:00 - error: Unhandled rejection: WS2P connection timeout
2017-09-29T16:18:34+00:00 - error: WS2P connection timeout
```

**Comment by M5oul** [comment]
Again due to WS2P:
```bash
2017-09-29T16:21:31+00:00 - info: ⬇ PEER ECTQrRoR
2017-09-29T16:21:31+00:00 - error:  httpCode=400, ucode=1015, message=Document already under treatment
2017-09-29T16:21:32+00:00 - info: ⬇ PEER ECTQrRoR
2017-09-29T16:21:32+00:00 - error:  httpCode=400, ucode=1015, message=Document already under treatment
2017-09-29T16:21:33+00:00 - info: ⬇ PEER ECTQrRoR
2017-09-29T16:21:33+00:00 - error:  httpCode=400, ucode=1015, message=Document already under treatment
2017-09-29T16:21:33+00:00 - info: WS2P: Could not connect to peer -------- using `WS2P 109.19.209.9 20900: WS2P connection timeout`
```
