### ISSUE TITLE
TypeError: res.clone

### ISSUE THREAD

**Issue by brabalan** [duniter/duniter#1134]
I got the following error a few days ago

```
    2017-09-30T08:29:14+02:00 - info: Block resolution: 0 potential blocks after current#56730…
    2017-09-30T08:38:03+02:00 - info: SIDE Block #56733-000007E2 added to the blockchain in 99 ms
    2017-09-30T08:38:03+02:00 - info: Block resolution: 0 potential blocks after current#56730…
    2017-09-30T08:38:03+02:00 - info: Fork resolution: 1 potential block(s) found…
    2017-09-30T08:38:04+02:00 - info: Fork resolution: 1 potential suite(s) found…
    2017-09-30T08:38:04+02:00 - info: Fork resolution: HEAD = block#56730
    2017-09-30T08:38:04+02:00 - info: Fork resolution: suite 1/1 (-> #56733-000007) revert to fork point block#56729
    2017-09-30T08:38:06+02:00 - info: Block #56730 added to the blockchain in 465 ms
    2017-09-30T08:38:06+02:00 - info: Fork resolution: suite 1/1 added block#56730-000000B1C37C6C75CC681D8784BE6C29D87BFF744DDBBBE0231EE850F700793B
    2017-09-30T08:38:06+02:00 - info: Block #56731 added to the blockchain in 236 ms
    2017-09-30T08:38:06+02:00 - info: Fork resolution: suite 1/1 added block#56731-0000013EB5C2380EE403BB8D66E91987BFAD77183F7591DEF6F2F4F4FC18E448
    2017-09-30T08:38:07+02:00 - info: Block #56732 added to the blockchain in 230 ms
    2017-09-30T08:38:07+02:00 - info: Fork resolution: suite 1/1 added block#56732-00000638578AB1F24F698B49CD4B2793DD21777F591608A173C36CE18B4904E6
    2017-09-30T08:38:07+02:00 - info: Block #56733 added to the blockchain in 278 ms
    2017-09-30T08:38:07+02:00 - info: Fork resolution: suite 1/1 added block#56733-000007E239A33304A6BCBC19F0E566A99FF98F92AD05EBE8673C0D210B1AB153
    2017-09-30T08:38:07+02:00 - info: Fork resolution: suite 1/1 reached HEAD + 3. Now rolling back.
    2017-09-30T08:38:09+02:00 - info: Block #56730 added to the blockchain in 112 ms
    2017-09-30T08:38:09+02:00 - info: Block #56730 added to the blockchain in 119 ms
    2017-09-30T08:38:09+02:00 - info: Block #56731 added to the blockchain in 146 ms
    2017-09-30T08:38:10+02:00 - info: Block #56732 added to the blockchain in 156 ms
    2017-09-30T08:38:10+02:00 - info: Block #56733 added to the blockchain in 249 ms
    2017-09-30T08:38:10+02:00 - error: Unhandled rejection: TypeError: res.clone is not a function
    2017-09-30T08:38:10+02:00 - error: TypeError: res.clone is not a function
    at Server. (/opt/duniter/server.js:293:66)
    at next (native)
    at /opt/duniter/server.js:7:71
    at __awaiter (/opt/duniter/server.js:3:12)
    at Server.emitDocument (/opt/duniter/server.js:292:16)
    at BlockchainService.pipe.es.mapSync (/opt/duniter/server.js:169:26)
    at Stream.write (/opt/duniter/node_modules/event-stream/index.js:204:20)
    at Stream.stream.write (/opt/duniter/node_modules/through/index.js:26:11)
    at BlockchainService.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at BlockchainService.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at BlockchainService.Readable.push (_stream_readable.js:134:10)
    at BlockchainService. (/opt/duniter/app/service/BlockchainService.js:218:22)
    at next (native)
    at fulfilled (/opt/duniter/app/service/BlockchainService.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

After that error my node got stuck computing the same block for 12 hours, until I restarted it. It is working fine now.

**Comment by librelois** [comment]
We should create a "fork resolution" label, but I don't have rights for that.

**Comment by librelois** [comment]
@brabalan it seems that your node makes an infinite ping-pong between two branches, the next time we would need to see your duniter.db file to understand what context can lead to this behaviour.

**Comment by c-geek** [comment]
IMO there is no ping-pong, the algorithm is not buggy but the code encounters an error at:

    2017-09-30T08:38:10+02:00 - error: Unhandled rejection: TypeError: res.clone is not a function
    2017-09-30T08:38:10+02:00 - error: TypeError: res.clone is not a function

which stops the resolution process.

**Comment by c-geek** [comment]
Par contre en effet avoir le duniter.db + wotb.bin (il faut les 2 absolument) permettrait de reproduire le bug.

**Comment by brabalan** [comment]
Je peux t'envoyer les deux (si c'est toujours utile sachant que le nœud a été redémarré). Il y a des données confidentielles dedans ?

**Comment by c-geek** [comment]
Enfin si un restart a corrigé le problème, non ça ne va pas nous aider !

Ce problème de res.clone arrive typiquement du fait qu'il y a encore plein de `any` dans le code, et donc que la variable `res` ne possède pas le type attendu. Mais c'est un travail de longue haleine que de remplacer par des types stricts tous ces any.

Après je me trompe peut-être, mais il me semble bien que le typage pourrait révéler l'erreur initiale.

**Comment by brabalan** [comment]
OK, je reste vigilant si cela se reproduit. Bon courage pour le typage !
