### ISSUE TITLE
OpenBSD build

### ISSUE THREAD

**Issue by B4rb3rouss** [duniter/duniter#1150]
Hello,
Do you plan an OpenBSD build, or any advice to compile duniter on this platform?

Regards.

**Comment by Insoleet** [comment]
Duniter uses Vagrant to produces builds. It should be easy to add OpenBSD to supported OS :  

 - https://app.vagrantup.com/ryanmaclean/boxes/openbsd-6.0
 - https://github.com/duniter/duniter/blob/master/release/scripts/build.sh

Contributions are welcome !

**Comment by B4rb3rouss** [comment]
Before producing a build, I tried to compile duniter on OpenBSD 6.2 acording to instructions.
- Dowloaded src tarball
- ran `npm install`

It fails. See log attached.

node version is 6.11.2.
[npm-debug.log](https://github.com/duniter/duniter/files/1374688/npm-debug.log)

**Comment by c-geek** [comment]
Please replace `npm install` by `yarn`. https://yarnpkg.com/lang/en/docs/install/

**Comment by B4rb3rouss** [comment]
yarn isn't avaiable on OpenBSD.

**Comment by c-geek** [comment]
npm install --global yarn

Does this work?

**Comment by B4rb3rouss** [comment]
yes, it works. thanks
Let's build duniter now (or try to)

**Comment by B4rb3rouss** [comment]
nope, still a problem with sqlite : 

```
yarn install v1.2.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "bl@0.7.0" has unmet peer dependency "stream-browserify@*".
[5/5] Building fresh packages...
[1/5] ⢀ heapdump: info ok
[2/5] ⢀ naclb: /usr/bin/clang++ '-DNODE_GYP_MODULE_NAME=naclb' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFIL
[3/5] ⢀ scryptb: https://scryptb.s3-eu-central-1.amazonaws.com/v6.0.4/Release/scryptb-v6.0.4-node-v48-openbsd-x64.tar.gz
[4/5] ⢀ sqlite3: stack
error /home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.34
node-pre-gyp info using node@6.11.2 | openbsd | x64
node-pre-gyp info check checked for "/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/lib/binding/node-v48-openbsd-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v48-openbsd-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v48-openbsd-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v48-openbsd-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@6.11.2 (node-v48 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v48-openbsd-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.11.2 | openbsd | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.11.2 | openbsd | x64
gyp info spawn /usr/local/bin/python2.7
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/xavier/.node-gyp/6.11.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/xavier/.node-gyp/6.11.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.11.2 | openbsd | x64
gyp info spawn gmake
gyp info spawn args [ 'BUILDTYPE=Release', 'V=1', '-C', 'build' ]
gmake : on entre dans le répertoire « /home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/build »
  LD_LIBRARY_PATH=/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/build/Release/lib.host:/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps; mkdir -p /home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/build/Release/obj/gen/sqlite-autoconf-3090100; python ./extract.py ./sqlite-autoconf-3090100.tar.gz "/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/build/Release/obj/gen"
/bin/sh: python: not found
gmake: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c] Error 127
gmake : on quitte le répertoire « /home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/build »
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:278:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System OpenBSD 6.2
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/lib/binding/node-v48-openbsd-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/lib/binding/node-v48-openbsd-x64"
gyp ERR! cwd /home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/lib/binding/node-v48-openbsd-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/lib/binding/node-v48-openbsd-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/xavier/geek/duniter/duniter-1.5.4/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System OpenBSD 6.2
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/xavier/geek/duniter/duniter-1.5.4/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok 
```

**Comment by c-geek** [comment]
Yes, when a pre-built binary like sqlite3 isn't available, yarn tries to compile it directly.

See the error, it is:

    /bin/sh: python: not found

You need Python 2.

**Comment by B4rb3rouss** [comment]
Ok, I have python but never set up a default version.
After `ln -s /usr/local/bin/python2.7 /usr/local/bin/python`, it goes further and works.
Thank you.

For the record : 

```
# pkg_add node
# npm install --global yarn
# ln -s /usr/local/bin/python2.7 /usr/local/bin/python
$ cd duniter*
$ yarn
```

**Comment by c-geek** [comment]
I keep the issue opened, OpenBSD users have the right to have a pre-built binary :-)

Thanks for the investigation! It will same us time.

**Comment by B4rb3rouss** [comment]
Oh, right. I'll try a build as soon as possible. For now I learn to use duniter.

**Comment by B4rb3rouss** [comment]
well, it seems the web interface no longer exists, but it is mentionned in doc. I keep digging a little.

**Comment by c-geek** [comment]
It's now an external, optional module.

You can add it to your installation easily:

    yarn add duniter-ui

Then, you can start your node with the WebUI using `duniter direct_webstart` or `duniter webstart` (daemon mode).
