### ISSUE TITLE
Error: SQL error "undefined" on INIT queries "PRAGMA case_sensitive_like=ON"

### ISSUE THREAD

**Issue by KindlyFire** [duniter/duniter#1163]
Executing `./duniter.sh` yields nothing. Executing `./node bin/duniter` outputs the following:

```
2017-10-26T07:05:12+02:00 - debug: Plugging file system...
2017-10-26T07:05:12+02:00 - debug: Loading conf...
2017-10-26T07:05:12+02:00 - warn: No configuration loaded
2017-10-26T07:05:13+02:00 - info: Checking UPnP features...
2017-10-26T07:05:13+02:00 - info: IPv6: <ipv6>
2017-10-26T07:05:13+02:00 - info: Local IPv4: <ipv4>
2017-10-26T07:05:13+02:00 - info: Remote IPv4: <ipv4>
2017-10-26T07:05:13+02:00 - info: UPnP: Yes
2017-10-26T07:05:13+02:00 - info: DNS: No
2017-10-26T07:05:13+02:00 - debug: Configuration saved.
2017-10-26T07:05:13+02:00 - debug: Opening SQLite database "/home/kindly/.config/duniter/duniter_default/duniter.db"...
2017-10-26T07:05:13+02:00 - error:  Error: SQL error "undefined" on INIT queries "PRAGMA case_sensitive_like=ON"
    at Error (native)
    at Database.sqlite.exec (/home/kindly/Documents/duniter/app/lib/dal/drivers/SQLiteDriver.js:31:39)
    at Database.replacement (/home/kindly/Documents/duniter/node_modules/sqlite3/lib/trace.js:20:31)
```

I am running the v1.5.9 release on Solus.

**Comment by Insoleet** [comment]
Do you use nvm ?

What is solus exactly ?

**Comment by c-geek** [comment]
This is an error caused by SQLite library. It might not have compiled correctly during your installation.

Did you use `yarn` for compiling?

**Comment by KindlyFire** [comment]
When I say solus I mean the Linux distribution I am using. I downloaded the client from [here](https://github.com/duniter/duniter/releases/tag/v1.5.9), selecting `duniter-desktop-v1.5.9-linux-x64.tar.gz`.

I ran node from the binary provided in the package, using the same command the script `./duniter.sh` would do, and posted the output in my first post.

**Comment by librelois** [comment]
@KindlyFire  encounter the same problem with duniter 1.6.14 ?

**Comment by KindlyFire** [comment]
Can confirm the same error still appears with duniter `1.6.14`.

![screenshot from 2017-11-17 20-48-17](https://user-images.githubusercontent.com/10267586/32965998-b516b320-cbd8-11e7-8415-bbfec2cc22e5.png)
