### ISSUE TITLE
The proof-of-work generation was canceled: [object Object]

### ISSUE THREAD

**Issue by myckeul** [duniter/duniter#1172]
Après quelques semaines d'activités mon noeud Duniter a commencé à planter (deux fois en quelques jours). Pour info, version 1.5.9 sur une Debian

Voici une trace des logs : 

```
2017-11-02T10:37:30+01:00 - info: Block #65610 added to the blockchain in 497 ms
2017-11-02T10:37:30+01:00 - info: Cancelling the work on PoW cluster
2017-11-02T10:37:31+01:00 - info: Block resolution: 1 potential blocks after current#65610...
2017-11-02T10:37:31+01:00 - info: POST Block block#65610
2017-11-02T10:37:31+01:00 - info: Block #65611 added to the blockchain in 488 ms
2017-11-02T10:37:31+01:00 - info: Cancelling the work on PoW cluster
2017-11-02T10:37:31+01:00 - info: Block resolution: 1 potential blocks after current#65611...
2017-11-02T10:37:31+01:00 - info: POST Block block#65611
2017-11-02T10:37:32+01:00 - info: Block #65612 added to the blockchain in 465 ms
2017-11-02T10:37:32+01:00 - info: Cancelling the work on PoW cluster
2017-11-02T10:37:32+01:00 - info: Block resolution: 1 potential blocks after current#65612...
2017-11-02T10:37:32+01:00 - info: POST Block block#65612
2017-11-02T10:37:32+01:00 - warn: Pulling not finished after 10000 ms, continue PoW
2017-11-02T10:37:32+01:00 - warn: Pulling done. Continue proof-of-work loop.
2017-11-02T10:37:32+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:32+01:00 - info: Block #65613 added to the blockchain in 457 ms
2017-11-02T10:37:32+01:00 - info: Cancelling the work on PoW cluster
2017-11-02T10:37:32+01:00 - info: Cancelling the work on PoW cluster
2017-11-02T10:37:32+01:00 - info: Block resolution: 1 potential blocks after current#65613...
2017-11-02T10:37:32+01:00 - warn:  TypeError: Cannot read property 'issuersFrame' of null
    at Function.<anonymous> (/opt/duniter/app/lib/indexer.js:931:53)
    at next (native)
    at /opt/duniter/app/lib/indexer.js:7:71
    at __awaiter (/opt/duniter/app/lib/indexer.js:3:12)
    at Function.preparePersonalizedPoW (/opt/duniter/app/lib/indexer.js:923:16)
    at BlockchainContext.<anonymous> (/opt/duniter/app/lib/computation/BlockchainContext.js:83:27)
    at next (native)
    at fulfilled (/opt/duniter/app/lib/computation/BlockchainContext.js:4:58)
2017-11-02T10:37:33+01:00 - info: POST Block block#65613
2017-11-02T10:37:33+01:00 - info: Block #65614 added to the blockchain in 507 ms
2017-11-02T10:37:33+01:00 - info: Cancelling the work on PoW cluster
2017-11-02T10:37:33+01:00 - warn: Blockchain changed!
2017-11-02T10:37:33+01:00 - info: Block resolution: 1 potential blocks after current#65614...
2017-11-02T10:37:33+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:33+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:33+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:33+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:33+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:33+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:33+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:33+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:33+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - info: POST Block block#65614
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
2017-11-02T10:37:34+01:00 - warn: The proof-of-work generation was canceled: [object Object]
```

Ca tourne en boucle ainsi, un restart permet de débloquer la situation quelques secondes puis ça recommence ... 

Du coup mon noeud reste bloqué sur un bloc et se désynchronise du réseau.

J'ai essayé de supprimer le .config/duniter/ puis de refaire une config et synchro complète et ça a recommencé au bout de quelques jours.

**Comment by myckeul** [comment]
En complément, si j'essaye de faire un sync j'ai une erreur puis le second sync passe ensuite : 

```
2017-11-02T10:47:56+01:00 - debug: Plugging file system...
2017-11-02T10:47:56+01:00 - debug: Loading conf...
2017-11-02T10:47:56+01:00 - debug: Configuration saved.
2017-11-02T10:47:56+01:00 - debug: Opening SQLite database "/home/michael/.config/duniter/duniter_default/duniter.db"...
2017-11-02T10:47:56+01:00 - debug: Upgrade database...
2017-11-02T10:47:56+01:00 - debug: Reverting block #65710...
2017-11-02T10:47:56+01:00 - debug: Trying to close SQLite...
2017-11-02T10:47:56+01:00 - error:  TypeError: Cannot read property 'transactions' of null
    at DuniterBlockchain.<anonymous> (/opt/duniter/app/lib/blockchain/DuniterBlockchain.js:443:36)
    at next (native)
    at /opt/duniter/app/lib/blockchain/DuniterBlockchain.js:7:71
    at __awaiter (/opt/duniter/app/lib/blockchain/DuniterBlockchain.js:3:12)
    at DuniterBlockchain.undoDeleteTransactions (/opt/duniter/app/lib/blockchain/DuniterBlockchain.js:442:16)
    at DuniterBlockchain.<anonymous> (/opt/duniter/app/lib/blockchain/DuniterBlockchain.js:406:24)
    at next (native)
    at fulfilled (/opt/duniter/app/lib/blockchain/DuniterBlockchain.js:4:58)

```

**Comment by Insoleet** [comment]
Ton noeud est en 1.5.9 ?

**Comment by myckeul** [comment]
Oui, il est bien en 1.5.9

**Comment by Insoleet** [comment]
C'est un bug connu de la 1.5.9. Quand le noeud est coupé du réseau un certain temps ou a du retard, il peut avoir du mal à rattraper la chaine et planter lamentablement... 

Perso je reset data + sync quand ça m'arrive :/

**Comment by myckeul** [comment]
Ok ok bon bah on va faire comme ça en attendant la 1.6 stable alors ! 

Merci, je ferme cette issue
