### ISSUE TITLE
Initial synchronization seems to fail

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#372]
At the end of the sync, we get redirected to:

![image](https://cloud.githubusercontent.com/assets/969136/14047513/78c9df92-f2a8-11e5-84a2-b6ee37dc1406.png)

**Comment by c-geek** [comment]
Fixed by c234cc2891ebfaa415599f4540c32fa988030691.

**Comment by M5oul** [comment]
It happen for me with duniter0.20a33:
```fish
./nw 
[0330/182949:INFO:nw_package.cc(175)] ./nw
2016-03-30T18:29:51+02:00 - debug: Plugging file system...
2016-03-30T18:29:51+02:00 - info: uCoin web admin listening on http://localhost:9220
Failed to open file for reading : /home/moul/.config/duniter/duniter_default/wotb.bin
2016-03-30T18:29:51+02:00 - debug: Loading conf...
2016-03-30T18:29:51+02:00 - warn: No configuration loaded
2016-03-30T18:29:51+02:00 - debug: Loading crypto functions...
2016-03-30T18:29:53+02:00 - warn: No configuration loaded
2016-03-30T18:29:53+02:00 - warn: No configuration loaded
[10961:10961:0330/183014:ERROR:logging.h(813)] Failed to call method: org.freedesktop.DBus.ObjectManager.GetManagedObjects: object_path= /: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[10961:10961:0330/183014:ERROR:logging.h(813)] Failed to call method: org.freedesktop.DBus.ObjectManager.GetManagedObjects: object_path= /: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out
2016-03-30T18:30:30+02:00 - info: Checking UPnP features...
2016-03-30T18:30:30+02:00 - debug: Loading conf...
2016-03-30T18:30:30+02:00 - info: Connecting remote host...
2016-03-30T18:30:30+02:00 - info: Sync started.
2016-03-30T18:30:30+02:00 - debug: Loading crypto functions...
2016-03-30T18:30:30+02:00 - info: Downloading Blockchain...
2016-03-30T18:30:30+02:00 - info: Connecting to twiced.fr...
2016-03-30T18:30:30+02:00 - info: Cannot read property 'self' of null
2016-03-30T18:30:30+02:00 - error: TypeError: Cannot read property 'self' of null
    at /home/moul/projects/duniter/duniter-v0.20.0a33/sources/node_modules/vucoin/node_modules/form-data/node_modules/async/lib/async.js:28:48
    at Object.<anonymous> (/home/moul/projects/duniter/duniter-v0.20.0a33/sources/node_modules/vucoin/node_modules/form-data/node_modules/async/lib/async.js:1265:2)
    at Module._compile (module.js:431:34)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:375:32)
    at Function.Module._load (module.js:332:12)
    at Module.require (module.js:385:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/moul/projects/duniter/duniter-v0.20.0a33/sources/node_modules/vucoin/node_modules/form-data/lib/form_data.js:9:13)
    at Module._compile (module.js:431:34)
2016-03-30T18:30:30+02:00 - warn: Cannot read property 'self' of null
2016-03-30T18:30:46+02:00 - info: Checking UPnP features...
2016-03-30T18:30:46+02:00 - debug: Loading conf...
2016-03-30T18:30:46+02:00 - debug: Loading crypto functions...
2016-03-30T18:30:46+02:00 - info: Connecting remote host...
2016-03-30T18:30:46+02:00 - info: Sync started.
2016-03-30T18:30:46+02:00 - info: Downloading Blockchain...
2016-03-30T18:30:46+02:00 - info: Connecting to twiced.fr...
2016-03-30T18:30:46+02:00 - info: Cannot read property 'self' of null
2016-03-30T18:30:46+02:00 - error: TypeError: Cannot read property 'self' of null
    at /home/moul/projects/duniter/duniter-v0.20.0a33/sources/node_modules/vucoin/node_modules/form-data/node_modules/async/lib/async.js:28:48
    at Object.<anonymous> (/home/moul/projects/duniter/duniter-v0.20.0a33/sources/node_modules/vucoin/node_modules/form-data/node_modules/async/lib/async.js:1265:2)
    at Module._compile (module.js:431:34)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:375:32)
    at Function.Module._load (module.js:332:12)
    at Module.require (module.js:385:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/moul/projects/duniter/duniter-v0.20.0a33/sources/node_modules/vucoin/node_modules/form-data/lib/form_data.js:9:13)
    at Module._compile (module.js:431:34)
2016-03-30T18:30:46+02:00 - warn: Cannot read property 'self' of null
```

**Comment by c-geek** [comment]
Please remove your `~/.config/duniter` folder and try again, you might have old data conflicting with this version.

**Comment by M5oul** [comment]
I removed this folder before running sync.

**Comment by c-geek** [comment]
? why do you close it then?

**Comment by c-geek** [comment]
@vincentux still has the issue with alpha36

Environment: ArchLinux x86_64 Linux 4.4.6-1-MANJARO

**Comment by vincentux** [comment]
Je viens d'installer la nouvelle version (Duniter 0.20.0a45) j'ai bien supp les dossiers dans .config mais j'ai toujours cette erreur ...
- message d'erreur : https://framabin.org/?c62d250178a482f7#kZbXzMZLc4v3FGjs7t71dPLLDAyaswo6SnbFIo1yT2I=
- capture d'écran : https://framapic.org/4Tqb0gixH0RB/kyqBpdEqLEgH.png

**Comment by c-geek** [comment]
Merci @vincentux, je continue d'investiguer. Je souhaitais déjà faire ressortir les erreurs de manière plus explicite.

**Comment by M5oul** [comment]
Je ne rencontre plus le problème.
Si c’est bon de votre côté, on peut fermer l’issue.

**Comment by M5oul** [comment]
I think it's solved.
I close it.
Feel free to reopen.
