### ISSUE TITLE
Crash at resync

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#413]
When I restart my node 0.20.0.a57, it resync then crash:
```fish
 ./nw 
[0506/125718:INFO:nw_package.cc(175)] ./nw
Received signal 8 FPE_INTDIV 7f96c6eef1e4
#0 0x7f96c62b468b <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000001 r11: 0000000000000000
 r12: 00000e72c62ab628 r13: 00007f96a8965d9c r14: 00007fffbf8e6320 r15: 00000e72c62ab618
  di: 00000000000f4240  si: 0000000000000000  bp: 00000e72c62ab600  bx: 8000000000000000
  dx: 0000000000000000  ax: 00000000000f4240  cx: 0000000000000000  sp: 00007fffbf8e5f10
  ip: 00007f96c6eef1e4 efl: 0000000000010a83 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
2016-05-06T12:57:22+02:00 - debug: Plugging file system...
Received signal 8 FPE_INTDIV 7fe4682271e4
#0 0x7fe4675ec68b <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000001 r11: 0000000000000000
 r12: 00001dbd828cd628 r13: 00007fe449c9dd9c r14: 00007ffc12b7f5e0 r15: 00001dbd828cd618
  di: 00000000000f4240  si: 0000000000000000  bp: 00001dbd828cd600  bx: 8000000000000000
  dx: 0000000000000000  ax: 00000000000f4240  cx: 0000000000000000  sp: 00007ffc12b7f1d0
  ip: 00007fe4682271e4 efl: 0000000000010a83 cgf: 2016-05-06T12:57:22+02:00 - info: uCoin web admin listening on http://localhost:9220
0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Received signal 8 FPE_INTDIV 7ffa5fb121e4
#0 0x7ffa5eed768b <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000001 r11: 0000000000000000
 r12: 00002d14250d85a8 r13: 00007ffa41588d9c r14: 00007ffe825b5490 r15: 00002d14250d8598
  di: 00000000000f4240  si: 0000000000000000  bp: 00002d14250d8580  bx: 8000000000000000
  dx: 0000000000000000  ax: 00000000000f4240  cx: 0000000000000000  sp: 00007ffe825b5080
  ip: 00007ffa5fb121e4 efl: 0000000000010a83 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
[3640:3640:0506/125722:ERROR:webgraphicscontext3d_command_buffer_impl.cc(269)] Failed to initialize GLES2Implementation.
2016-05-06T12:57:22+02:00 - debug: Loading conf...
2016-05-06T12:57:22+02:00 - debug: Loading crypto functions...
[3598:3613:0506/125722:ERROR:browser_gpu_channel_host_factory.cc(145)] Failed to create channel.
2016-05-06T12:57:23+02:00 - debug: Upgrade database...
2016-05-06T12:57:24+02:00 - info: uCoin server listening on http://192.168.1.29:56767
2016-05-06T12:57:24+02:00 - info: uCoin server listening on http://2a01:e34:ee36:b2d0:ea9a:8fff:fe2b:d66d:56767
2016-05-06T12:57:24+02:00 - info: Node version: 0.20.0a57
2016-05-06T12:57:24+02:00 - info: Node pubkey: J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
2016-05-06T12:57:24+02:00 - info: Crawling the network...
2016-05-06T12:57:24+02:00 - info: Storing self peer...
2016-05-06T12:57:24+02:00 - info: External access: 78.227.107.45:56767
2016-05-06T12:57:24+02:00 - debug: Generating server's peering entry based on block#3412...
2016-05-06T12:57:25+02:00 - info: Next peering signal in 30 min
2016-05-06T12:57:25+02:00 - trace: Checking if node 5ocqzy is UP... (test-net.duniter.fr:9201) 
2016-05-06T12:57:25+02:00 - debug: --> new Peer to be sent to 5 peer(s)
2016-05-06T12:57:25+02:00 - info: POST Peer J78bPUvLjx
2016-05-06T12:57:25+02:00 - debug:  `--> to peer HnFcSms8jz [member] (88.174.120.187:9330)
2016-05-06T12:57:25+02:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-9A-D]... (CPU usage set to 20%)
2016-05-06T12:57:25+02:00 - trace: Peer 5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of is DOWN (ECONNREFUSED)
2016-05-06T12:57:25+02:00 - debug: Will check that node 5ocqzy (test-net.duniter.fr:9201) is UP in 60 min...
2016-05-06T12:57:25+02:00 - info: Pulling blocks from the network...
2016-05-06T12:57:25+02:00 - trace: Try with 88.174.120.187:9331 4jT89q
2016-05-06T12:57:25+02:00 - debug: --> new Peer to be sent to 5 peer(s)
2016-05-06T12:57:25+02:00 - info: POST Peer J78bPUvLjx
2016-05-06T12:57:25+02:00 - debug:  `--> to peer HnFcSms8jz [member] (88.174.120.187:9330)
2016-05-06T12:57:25+02:00 - debug:  `--> to peer 8Fi1VSTbjk [member] (testnet.duniter.inso.ovh:80)
2016-05-06T12:57:25+02:00 - debug:  `--> to peer EBHoJrsjX5 [------] (88.174.120.187:40864)
2016-05-06T12:57:25+02:00 - debug:  `--> to peer 8Fi1VSTbjk [member] (testnet.duniter.inso.ovh:80)
2016-05-06T12:57:25+02:00 - debug: Peer 4jT89q has forked
2016-05-06T12:57:25+02:00 - debug:  `--> to peer EBHoJrsjX5 [------] (88.174.120.187:40864)
2016-05-06T12:57:25+02:00 - debug:  `--> to peer 4jT89qUKAu [------] (88.174.120.187:9331)
2016-05-06T12:57:25+02:00 - trace: Try with 88.174.120.187:9332 AZ2JPA
2016-05-06T12:57:26+02:00 - debug:  `--> to peer 4jT89qUKAu [------] (88.174.120.187:9331)
2016-05-06T12:57:26+02:00 - debug:  `--> to peer AZ2JPAUch9 [------] (88.174.120.187:9332)
2016-05-06T12:57:26+02:00 - debug: Peer AZ2JPA has forked
2016-05-06T12:57:26+02:00 - debug:  `--> to peer AZ2JPAUch9 [------] (88.174.120.187:9332)
2016-05-06T12:57:26+02:00 - trace: Try with 88.174.120.187:40864 EBHoJr
2016-05-06T12:57:26+02:00 - debug: Peer EBHoJr has forked
2016-05-06T12:57:26+02:00 - trace: Try with 88.164.245.189:8999 H9Copf
2016-05-06T12:57:26+02:00 - debug: Peer H9Copf has forked
2016-05-06T12:57:26+02:00 - trace: Try with 88.164.245.189:8999 6qg4aJ
2016-05-06T12:57:27+02:00 - debug: Peer 6qg4aJ has forked
2016-05-06T12:57:27+02:00 - trace: Try with testnet.duniter.inso.ovh:80 8Fi1VS
2016-05-06T12:57:27+02:00 - debug: Peer 8Fi1VS has forked
2016-05-06T12:57:27+02:00 - debug: Fork of 8Fi1VS has blockDistance 1185.00 ; timeDistance 1131.57 ; required is >= 30 for both values to try to follow the fork
2016-05-06T12:57:28+02:00 - info: Mesured max speed is ~413 tests/s. Proof will try with ~83 tests/s.
2016-05-06T12:57:29+02:00 - trace: SWITCH: 2 branches...
2016-05-06T12:57:29+02:00 - trace: SWITCH: 0 potential side chains...
2016-05-06T12:57:29+02:00 - trace: SWITCH: 2 branches...
2016-05-06T12:57:29+02:00 - trace: SWITCH: 0 potential side chains...
2016-05-06T12:57:29+02:00 - trace: SWITCH: 2 branches...
2016-05-06T12:57:29+02:00 - trace: SWITCH: 0 potential side chains...
…
[Cut ………………]
…
2016-05-06T12:57:34+02:00 - trace: SWITCH: 2 branches...
2016-05-06T12:57:34+02:00 - trace: SWITCH: 0 potential side chains...
2016-05-06T12:57:34+02:00 - trace: SWITCH: 2 branches...
2016-05-06T12:57:34+02:00 - trace: SWITCH: 0 potential side chains...
2016-05-06T12:57:34+02:00 - trace: SWITCH: 2 branches...
2016-05-06T12:57:34+02:00 - trace: SWITCH: 0 potential side chains...
Error: channel closed
    at process.target.send (internal/child_process.js:523:16)
    at /home/moul/projects/duniter/sources/app/lib/proof.js:100:23
    at fn (/home/moul/projects/duniter/sources/node_modules/async/lib/async.js:746:34)
    at /home/moul/projects/duniter/sources/node_modules/async/lib/async.js:1213:16
    at /home/moul/projects/duniter/sources/node_modules/async/lib/async.js:166:37
    at /home/moul/projects/duniter/sources/node_modules/async/lib/async.js:706:43
    at /home/moul/projects/duniter/sources/node_modules/async/lib/async.js:167:37
    at /home/moul/projects/duniter/sources/node_modules/async/lib/async.js:1209:30
    at ._onTimeout (/home/moul/projects/duniter/sources/app/lib/proof.js:96:17)
    at Timer.listOnTimeout (timers.js:92:15)
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: channel closed
    at process.target.send (internal/child_process.js:523:16)
    at process.<anonymous> (/home/moul/projects/duniter/sources/app/lib/proof.js:19:11)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process._fatalException (node.js:275:26)
```

**Comment by M5oul** [comment]
I could reproduce it:
```fish
2016-05-07T15:06:40+02:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-9A-B]... (CPU usage set to 10%)
2016-05-07T15:06:40+02:00 - trace: Block median time +459
2016-05-07T15:06:40+02:00 - trace: Block time +459
2016-05-07T15:06:40+02:00 - info: Block #3747 added to the blockchain in 235 ms
Error: channel closed
    at process.target.send (internal/child_process.js:523:16)
    at /home/moul/projects/duniter/sources/app/lib/proof.js:100:23
    at fn (/home/moul/projects/duniter/sources/node_modules/async/lib/async.js:746:34)
    at /home/moul/projects/duniter/sources/node_modules/async/lib/async.js:1213:16
    at /home/moul/projects/duniter/sources/node_modules/async/lib/async.js:166:37
    at /home/moul/projects/duniter/sources/node_modules/async/lib/async.js:706:43
    at /home/moul/projects/duniter/sources/node_modules/async/lib/async.js:167:37
    at /home/moul/projects/duniter/sources/node_modules/async/lib/async.js:1209:30
    at ._onTimeout (/home/moul/projects/duniter/sources/app/lib/proof.js:96:17)
    at Timer.listOnTimeout (timers.js:92:15)
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: channel closed
    at process.target.send (internal/child_process.js:523:16)
    at process.<anonymous> (/home/moul/projects/duniter/sources/app/lib/proof.js:19:11)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process._fatalException (node.js:275:26)
```

**Comment by c-geek** [comment]
I will rewrite the proof-of-work module.

**Comment by c-geek** [comment]
Fixed in the [latest release alpha66](https://github.com/duniter/duniter/releases).
