### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#431]
My node became crazy and was unreachable, I had to stop it because following logs were displayed many times:
```fish
2016-05-14T14:38:35+02:00 - warn: Waiting 0s before starting computing next block...
2016-05-14T14:38:35+02:00 - info: 88.174.120.187 - GET /blockchain/current HTTP/1.1 200 1413 - 0.910 ms
2016-05-14T14:38:35+02:00 - error:  TypeError: Cannot read property 'powMin' of undefined
    at /home/moul/projects/duniter/sources/app/lib/rules/global_rules.js:740:24
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:423:9)
2016-05-14T14:38:35+02:00 - info: 88.174.120.187 - GET /blockchain/current HTTP/1.1 200 1413 - 1.160 ms
2016-05-14T14:38:35+02:00 - info: 88.174.120.187 - GET /blockchain/current HTTP/1.1 200 1413 - 0.809 ms
2016-05-14T14:38:35+02:00 - info: 88.174.120.187 - GET /blockchain/current HTTP/1.1 200 1413 - 0.686 ms
2016-05-14T14:38:35+02:00 - warn: Waiting 0s before starting computing next block...
2016-05-14T14:38:35+02:00 - error: ERROR >> UPDATE peer SET `version` = ?, `currency` = ?, `status` = ?, `statusTS` = ?, `hash` = ?, `first_down` = ?, `last_try` = ?, `pubkey` = ?, `block` = ?, `signature` = ?, `endpoints` = ?, `raw` = ? WHERE `pubkey` = ? [2,"test_net","DOWN",1463038506,"19E711D8BF91F96777F16330A7E673718D0D5AFEB5E3E232253B56D02729F68D",1463229492477,1463229515651,"8rH6xuqXds7m1RD1i6BJdCnUirkeFhKULdts8iFbrJbF","5284-0000558BB7A45F7B029303B2CC47E9382F2D5E79783BAC6E318CF401457D89E3","lelrDR1haRZU4loljKDS/DU4ymgX0iv88UbDvhrky8R8yjO/h5ozzhYK59fRsdtLBJzkG8tm0ZHDhAdqs0DBBA==","[\"BASIC_MERKLED_API moul.re 78.227.107.45 2a01:e34:ee36:b2d0:82fa:5bff:fe28:389f 31550\"]","Version: 2\nType: Peer\nCurrency: test_net\nPublicKey: 8rH6xuqXds7m1RD1i6BJdCnUirkeFhKULdts8iFbrJbF\nBlock: 5284-0000558BB7A45F7B029303B2CC47E9382F2D5E79783BAC6E318CF401457D89E3\nEndpoints:\nBASIC_MERKLED_API moul.re 78.227.107.45 2a01:e34:ee36:b2d0:82fa:5bff:fe28:389f 31550\n","8rH6xuqXds7m1RD1i6BJdCnUirkeFhKULdts8iFbrJbF"] Error: SQLITE_CANTOPEN: unable to open database file
    at Error (native)
2016-05-14T14:38:35+02:00 - error:  TypeError: Cannot read property 'powMin' of undefined
    at /home/moul/projects/duniter/sources/app/lib/rules/global_rules.js:740:24
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:423:9)
2016-05-14T14:38:35+02:00 - warn: Waiting 0s before starting computing next block...
2016-05-14T14:38:35+02:00 - error: ERROR >> UPDATE peer SET `version` = ?, `currency` = ?, `status` = ?, `statusTS` = ?, `hash` = ?, `first_down` = ?, `last_try` = ?, `pubkey` = ?, `block` = ?, `signature` = ?, `endpoints` = ?, `raw` = ? WHERE `pubkey` = ? [2,"test_net","DOWN",1463038506,"19E711D8BF91F96777F16330A7E673718D0D5AFEB5E3E232253B56D02729F68D",1463229492477,1463229515684,"8rH6xuqXds7m1RD1i6BJdCnUirkeFhKULdts8iFbrJbF","5284-0000558BB7A45F7B029303B2CC47E9382F2D5E79783BAC6E318CF401457D89E3","lelrDR1haRZU4loljKDS/DU4ymgX0iv88UbDvhrky8R8yjO/h5ozzhYK59fRsdtLBJzkG8tm0ZHDhAdqs0DBBA==","[\"BASIC_MERKLED_API moul.re 78.227.107.45 2a01:e34:ee36:b2d0:82fa:5bff:fe28:389f 31550\"]","Version: 2\nType: Peer\nCurrency: test_net\nPublicKey: 8rH6xuqXds7m1RD1i6BJdCnUirkeFhKULdts8iFbrJbF\nBlock: 5284-0000558BB7A45F7B029303B2CC47E9382F2D5E79783BAC6E318CF401457D89E3\nEndpoints:\nBASIC_MERKLED_API moul.re 78.227.107.45 2a01:e34:ee36:b2d0:82fa:5bff:fe28:389f 31550\n","8rH6xuqXds7m1RD1i6BJdCnUirkeFhKULdts8iFbrJbF"] Error: SQLITE_CANTOPEN: unable to open database file
    at Error (native)
2016-05-14T14:38:35+02:00 - error:  TypeError: Cannot read property 'powMin' of undefined
    at /home/moul/projects/duniter/sources/app/lib/rules/global_rules.js:740:24
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:423:9)
2016-05-14T14:38:35+02:00 - warn: Waiting 0s before starting computing next block...
2016-05-14T14:38:35+02:00 - error:  TypeError: Cannot read property 'powMin' of undefined
    at /home/moul/projects/duniter/sources/app/lib/rules/global_rules.js:740:24
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:423:9)
2016-05-14T14:38:35+02:00 - warn: Waiting 0s before starting computing next block...
2016-05-14T14:38:35+02:00 - error:  TypeError: Cannot read property 'powMin' of undefined
    at /home/moul/projects/duniter/sources/app/lib/rules/global_rules.js:740:24
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:423:9)
```

It happen between this blocks:
```fish
2016-05-14T14:37:56+02:00 - info: Done: 0000560F682EBAFD9ECCA21B5AD6F762BFF3E65BDD699F7127C4B693E8238363 in 406.44s (117536 tests, ~289.19 tests/s)
2016-05-14T14:37:56+02:00 - info: 88.174.120.187 - GET /blockchain/current HTTP/1.1 200 1411 - 0.872 ms
--
2016-05-14T14:38:02+02:00 - info: Done: 000065FA60FD6839F2153782268AE3605786914F4EC2A373CFEB6C1DDEF53CAB in 4.31s (1229 tests, ~285.08 tests/s)
2016-05-14T14:38:02+02:00 - error: ERROR >> INSERT INTO block (`fork`,`hash`,`inner_hash`,`signature`,`currency`,`issuer`,`parameters`,`previousHash`,`previousIssuer`,`version`,`membersCount`,`monetaryMass`,`UDTime`,`medianTime`,`dividend`,`unitbase`,`time`,`powMin`,`number`,`nonce`,`transactions`,`certifications`,`identities`,`joiners`,`actives`,`leavers`,`revoked`,`excluded`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?); [false,"000065FA60FD6839F2153782268AE3605786914F4EC2A373CFEB6C1DDEF53CAB","7E249CF61B6C4B82F61848C5F89B441D2C5B314B65A7A47A9E5686C546302CCD","2UwaG+cvnV5KK2GI4V4ohmpdnyYJVXutSJpN5+V2Rno2uJBAP7LdOO7gNFgOcKO+zga3PUHUadGPQcbyRTI8Bw==","test_net","J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3","","0000560F682EBAFD9ECCA21B5AD6F762BFF3E65BDD699F7127C4B693E8238363","J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3",2,19,"15700000",null,1463228524,null,0,1463229481,69,5807,1229,"[]","[]","[]","[]","[]","[]","[]","[]"] Error: SQLITE_CANTOPEN: unable to open database file
--
2016-05-14T14:43:32+02:00 - info: Done: 00005EF1D2CEFAC3105A6DE78DFEFEB511A275C69DFC76C679F53E75B077D9C3 in 250.38s (77358 tests, ~308.96 tests/s)
2016-05-14T14:43:32+02:00 - info: Block #5807 added to the blockchain in 76 ms
```

**Comment by M5oul** [comment]
It seems to be linked to proof-of-work calculation.
My identity is the only one generating since this incident.
As I restarted it, it generate 37++ sharpened blocks #5807 to #5844 ++:
```fish
curl moul.re:31550/blockchain/difficulties
{
  "block": 5845,
  "levels": [
    {
      "uid": "moul",
      "level": 70
    }
  ]
}⏎
```

**Comment by c-geek** [comment]
For your initial error, it seems like your database was accessed concurrently, by more than one Duniter program.

When you say "I restarted it", do you mean just "restart" or also "reset + sync"?

Also, you are no more alone generating blocks, I restarted & resynced my node so it could generate blocks again. Probably our nodes generated a wrong block, that's why I added #432, so we can check if the node do generates wrong blocks.

However the better would be the problem to occur again so I can dump my database for debug purposes. Sadly, I did not have this reflex yesterday and reseted my database with no backup. Have to wait for this bug again.

**Comment by M5oul** [comment]
> When you say "I restarted it", do you mean just "restart" or also "reset + sync"?

I only restarted it.

**Comment by Insoleet** [comment]
> However the better would be the problem to occur again so I can dump my database for debug purposes. Sadly, I did not have this reflex yesterday and reseted my database with no backup. Have to wait for this bug again.

I probably have my database which reproduces the bug.

**Comment by c-geek** [comment]
@Insoleet so could you zip the whole (duniter.db, stats.json, wotb.bin, indicators/) and upload it somewhere? (http://up.twiced.fr for example)

**Comment by Insoleet** [comment]
Here you go : http://up.twiced.fr/f.php?h=077HHQ6_

**Comment by c-geek** [comment]
Ahem ... could you do it again @Insoleet please?

**Comment by Insoleet** [comment]
Sure ^^ http://up.twiced.fr/f.php?h=0F7HvLQw

**Comment by c-geek** [comment]
Got this one :smile: thanks!

**Comment by c-geek** [comment]
Does it occur again for you @M5oul, @Insoleet ?

**Comment by M5oul** [comment]
I wasn't able to reproduce it.

**Comment by Insoleet** [comment]
Same for me...

**Comment by c-geek** [comment]
Ok, please reopen if it happens again.
