### ISSUE TITLE
Bug sur création de monnaie

### ISSUE THREAD

**Issue by myckeul** [duniter/duniter#475]
Hello,

Je pense avoir trouvé un bug lors de la création d'une nouvelle monnaie, voici les étapes que je  suis : 

>     duniter init
>     duniter wizard (nb de certification à 1)
>     duniter start

    j'inscris 2 membres et je les certifies mutuellement

>     duniter gen-root
>     duniter gen-next --check --show

En théorie, si j'ai bien tout compris, je ne dois pas être très loin ... seulement quand je lance le gen-root j'ai une erreur :

>     2016-06-07T22:45:04+02:00 - debug: Block to be sent: #0 (2 newcomers, 2 certifications)
>     2016-06-07T22:45:04+02:00 - info: Generating proof-of-work with NaN leading zeros followed by [0-undefined]... (CPU usage set to 60%)
>     2016-06-07T22:45:14+02:00 - info: Mesured max speed is ~110 tests/s. Proof will try with ~66 tests/s.
>     TypeError: Cannot read property 'match' of undefined
>     at async.waterfall.process.send.found (/opt/duniter/sources/app/lib/proof.js:84:39)
>     at fn (/opt/duniter/sources/node_modules/async/lib/async.js:746:34)
>     at /opt/duniter/sources/node_modules/async/lib/async.js:1213:16
>     at /opt/duniter/sources/node_modules/async/lib/async.js:166:37
>     at /opt/duniter/sources/node_modules/async/lib/async.js:706:43
>     at /opt/duniter/sources/node_modules/async/lib/async.js:167:37
>     at Object.async.waterfall (/opt/duniter/sources/node_modules/async/lib/async.js:710:44)
>     at /opt/duniter/sources/app/lib/proof.js:64:17
>     at Object.async.whilst (/opt/duniter/sources/node_modules/async/lib/async.js:792:13)
>     at async.waterfall.block.signature (/opt/duniter/sources/app/lib/proof.js:61:13)
>     2016-06-07T22:45:14+02:00 - error: TypeError: Cannot read property 'nonce' of undefined
>     at ChildProcess. (/opt/duniter/sources/app/lib/blockProver.js:143:47)
>     at emitTwo (events.js:100:13)
>     at ChildProcess.emit (events.js:185:7)
>     at handleMessage (internal/child_process.js:718:10)
>     at Pipe.channel.onread (internal/child_process.js:444:11)

Le "NaN" me laisse assez perplexe ...

La solution que j'ai trouvé pour réussir à lancer la monnaie est de passer par la GUI Web et de faire le paramétrage ainsi, à la fin je fais le TRY, j'accepte le bloc et ça passe ... mais j'aimerais pouvoir le faire en CLI, ça serait plus pratique.

Ma version de duniter : 0.20.0dev (package debian).

Merci d'avance !

**Comment by myckeul** [comment]
N'est pas un bug, manque juste de documentation ;)

Si j'ai un peu de temps j'essaye de préparer une petite doc à l'occasion
