### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#500]
I can't launch `duniter-v0.20.1a8-linux-x64.tar.gz`:
```fish
./nw/nw
module.js:466
    throw err;
    ^

Error: Cannot find module '/home/moul/projects/duniter/sources/node_modules/sqlite3b/lib/binding/Release/node-v48-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:464:15)
    at Function.Module._load (module.js:407:25)
    at Module.require (module.js:492:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/moul/projects/duniter/sources/node_modules/sqlite3b/lib/sqlite3.js:4:15)
    at Module._compile (module.js:565:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:482:32)
    at tryModuleLoad (module.js:441:12)
    at Function.Module._load (module.js:433:3)
```

**Comment by c-geek** [comment]
Yes, fixed by https://github.com/duniter/duniter/commit/b9f9387e8857b4a62695cb5b2ec7da0b4a749958.
