### ISSUE TITLE
Non-changing "warn: Too high difficulty: waiting for other members to write next block"

### ISSUE THREAD

**Issue by Idyllei** [duniter/duniter#508]
For a few days I have had the same message in the Duniter logs.

I have absolutely no idea why I am unable to help secure the blockchain even after waiting several days for others to contribute and have my own local difficulty lowered.

Is this a flaw in my own configuration or is it a problem with the protocol itself? (I have seen #492 so I know there is talk of changing the difficulty rules.)

NOTE: I am under a firewalled connection so I am unable to port-forward my node. I am working on setting up a dedicated server for such things, though.

My logs:

```
2016-08-01T12:37:00-04:00 warn Too high difficulty: waiting for other members to write next block
2016-08-01T12:37:10-04:00 info Duniter server stop listening
2016-08-01T12:37:10-04:00 info Duniter server stop listening
2016-08-01T12:37:10-04:00 info Proof-of-work computation STOPPED.
2016-08-01T12:37:10-04:00 info Duniter server listening on http://192.168.0.125:58983
2016-08-01T12:37:10-04:00 info Duniter server listening on http://fe80::65d3:2b98:6505:efe5:58983
2016-08-01T12:37:10-04:00 error Error: No interface for remote contact.
    at C:\Program Files (x86)\Duniter\sources\server.js:294:17
    at _fulfilled (C:\Program Files (x86)\Duniter\sources\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (C:\Program Files (x86)\Duniter\sources\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (C:\Program Files (x86)\Duniter\sources\node_modules\q\q.js:756:13)
    at C:\Program Files (x86)\Duniter\sources\node_modules\q\q.js:817:14
    at flush (C:\Program Files (x86)\Duniter\sources\node_modules\q\q.js:110:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2016-08-01T12:37:10-04:00 warn No interface for remote contact.
2016-08-01T12:37:10-04:00 warn Waiting 0s before starting computing next block...
2016-08-01T12:37:11-04:00 warn Too high difficulty: waiting for other members to write next block
```

**Comment by c-geek** [comment]
It is likely your node sucessfully computed a bloc once and is now waiting for other members to compute a block, but it does not see them for some reason.

This has been done for a while now (your block was issued on 29/07/2016 21h16, so ~3 days ago).

I suggest you to reset the node's data (`UI > Settings > Data > Reset`) + resync with a node (like `duniter.org` on port `8999`.

The problem with unreachable nodes is that we cannot forward blocks to them, so they need to manually pull blocks from the Internet. These last days [we had blocking issues](https://forum.duniter.org/t/nouvelle-version-0-20-3-disponible/1122/1) which made the network unstable, which may explains why your node failed at pulling the blocks it would have legitimally downloaded otherwise.
