### ISSUE TITLE
Network issues

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#512]
With the Duniter 0.21.3 desktop version, when I click on `Network` tab,

![capture du 2016-08-09 12-28-50](https://cloud.githubusercontent.com/assets/4758871/17513421/3153ae86-5e2d-11e6-9210-fee563fa1aca.png)

```fish
2016-08-09T12:27:13+02:00 - info: 192.168.0.10 - GET /network/peers HTTP/1.1 304 - - 4.290 ms
2016-08-09T12:27:14+02:00 - error: TypeError: Cannot set property 'documentType' of undefined
    at /home/moul/projects/duniter/sources/app/service/PeeringService.js:281:27
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2016-08-09T12:27:14+02:00 - warn: Cannot set property 'documentType' of undefined
2016-08-09T12:27:17+02:00 - error: TypeError: Cannot set property 'documentType' of undefined
    at /home/moul/projects/duniter/sources/app/service/PeeringService.js:281:27
```

I don't have a very good Internet connection and the node is not retrieving last blocks.

**Comment by M5oul** [comment]
I can't reproduce it with Duniter 0.22.0.

**Comment by M5oul** [comment]
I close It as I don't remember about it and I can't reproduce it.
