### ISSUE TITLE
ARM build 0.30.5 is missing co module

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#543]
```bash
sudo duniter webstart
Warning: module.js:341
Warning:     throw err;
Warning:     ^
Warning: 
Warning: Error: Cannot find module 'co'
Warning:     at Function.Module._resolveFilename (module.js:339:15)
Warning:     at Function.Module._load (module.js:290:25)
Warning:     at Module.require (module.js:367:17)
Warning:     at require (internal/module.js:16:19)
Warning:     at Object.<anonymous> (/opt/duniter/sources/app/lib/system/directory.js:3:14)
Warning:     at Module._compile (module.js:413:34)
Warning:     at Object.Module._extensions..js (module.js:422:10)
Warning:     at Module.load (module.js:357:32)
Warning:     at Function.Module._load (module.js:314:12)
Warning:     at Module.require (module.js:367:17)
```

**Comment by M5oul** [comment]
May be linked to https://github.com/duniter/duniter/commit/f29190acb55a8acb5b95126c6c61605a24e4e73d#diff-9be5cca8bd449065c6a68223017265f4R3

Strange, because `co` module is used other places.

**Comment by c-geek** [comment]
L'installation s'est mal déroulée, je refais et upload de nouveau le build ARM.

**Comment by c-geek** [comment]
I figured out the issue: the Rasperry PI 3 hadn't enough memory to process the Node.js package installation. Duniter took ~200MB memory, and 500MB left for building packages seems to be not enough.

**Comment by M5oul** [comment]
You could [add swap](https://github.com/YunoHost-Apps/searx_ynh/blob/master/scripts/install#L46-L49) to extend it.
