### ISSUE TITLE
Error on v0.30.12 at "config --autoconf" on debian 8 x64

### ISSUE THREAD

**Issue by b3j0f** [duniter/duniter#556]
Hi,

I installed the package v0.30.12 in order to create a new server node and after the installation finished without errors, I executed the command `duniter config --autoconf` and got this error:
```bash
2016-08-25T05:10:35-04:00 - debug: Plugging file system...
2016-08-25T05:10:35-04:00 - debug: Loading conf...
2016-08-25T05:10:35-04:00 - warn: No configuration loaded
2016-08-25T05:10:35-04:00 - debug: Loading crypto functions...
2016-08-25T05:10:35-04:00 - info: Checking UPnP features...
2016-08-25T05:10:37-04:00 - error:  TypeError: Cannot read property 'value' of undefined
    at getBestLocal (/opt/duniter/sources/app/lib/system/network.js:313:8)
    at Object.module.exports.getBestLocalIPv6 (/opt/duniter/sources/app/lib/system/network.js:22:27)
    at /opt/duniter/sources/app/lib/wizard.js:386:29
    at fn (/opt/duniter/sources/node_modules/async/lib/async.js:746:34)
    at /opt/duniter/sources/node_modules/async/lib/async.js:1213:16
    at /opt/duniter/sources/node_modules/async/lib/async.js:166:37
    at /opt/duniter/sources/node_modules/async/lib/async.js:706:43
    at /opt/duniter/sources/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/opt/duniter/sources/node_modules/async/lib/async.js:1206:34)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

Here is my ifconfig output if it can help (the server is on a proxmox container with debian 8 x64):

```bash
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:954 errors:0 dropped:0 overruns:0 frame:0
          TX packets:954 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:84130 (82.1 KiB)  TX bytes:84130 (82.1 KiB)

venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:94651 errors:0 dropped:0 overruns:0 frame:0
          TX packets:21295 errors:0 dropped:6 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:130214446 (124.1 MiB)  TX bytes:3515361 (3.3 MiB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:192.168.42.107  P-t-P:192.168.42.107  Bcast:192.168.42.107  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1

venet0:1  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:(hidden for safety reasons)  P-t-P:(hidden for safety reasons)  Bcast:(hidden for safety reasons)  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
```

**Comment by c-geek** [comment]
Fixed in 0.30.13 release.
