### ISSUE TITLE
UnitBase issue

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#588]
I checked the blockchain with `sync --cautious`, at 97%, upper than block 37500, `UnitBase` issue:
```bash
2016-09-12T00:52:12+02:00 - debug: Source CFE0E675FC2539963C5FA7078E803B4D1FB4120C8AEFABABF98698348B9FD23D:0 = false
2016-09-12T00:52:12+02:00 - debug: Source CFE0E675FC2539963C5FA7078E803B4D1FB4120C8AEFABABF98698348B9FD23D:1 = false
2016-09-12T00:52:12+02:00 - debug: Source CFE0E675FC2539963C5FA7078E803B4D1FB4120C8AEFABABF98698348B9FD23D:2 = false
2016-09-12T00:52:12+02:00 - debug: Source CFE0E675FC2539963C5FA7078E803B4D1FB4120C8AEFABABF98698348B9FD23D:17 = false
2016-09-12T00:52:12+02:00 - trace: Block median time +302
2016-09-12T00:52:12+02:00 - trace: Block time +120
2016-09-12T00:52:13+02:00 - trace: Link 141 -> 1
2016-09-12T00:52:13+02:00 - trace: Link 140 -> 0
2016-09-12T00:52:13+02:00 - trace: Link 141 X> 1
2016-09-12T00:52:13+02:00 - trace: Link 140 X> 0
2016-09-12T00:52:13+02:00 - trace: Link 141 -> 1
2016-09-12T00:52:13+02:00 - trace: Link 140 -> 0
2016-09-12T00:52:13+02:00 - trace: Link 141 X> 1
2016-09-12T00:52:13+02:00 - trace: Link 140 X> 0
2016-09-12T00:52:13+02:00 - info: UnitBase must be equal to previous unit base = 3
2016-09-12T00:52:13+02:00 - error: Error: UnitBase must be equal to previous unit base = 3
    at Error (native)
    at /home/moul/projects/duniter/app/lib/rules/global_rules.js:101:13
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:369:9)
```

That's why Test-net network is strange.

**Comment by M5oul** [comment]
Ok, I said a mistake with my not updated node. It's fixed with https://github.com/duniter/duniter/commit/af92202cbe1920e449153d23f678666a6412f0d1.
Finally, It seems my node sync well. Strange. I don't know from where come this problem on the network.

**Comment by c-geek** [comment]
I've made a full `sync --cautious` on duniter.org:8999 this morning using v0.30.16, and the blockchain is fine.

The problem is a combination of #585 and #587.
