### ISSUE TITLE
Timeout at sync

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#603]
I still encounter a timeout problem at sync with local and remote nodes with my build and pre-build packages:
```bash
Progress:

Download: [                    ] 0 %
Apply:    [                    ] 0 %

Status: ETIMEDOUT
All done.
```

```bash
2016-09-18T00:34:05+02:00 - info: Peer BASIC_MERKLED_API 163.172.175.76 2001:bc8:4400:2000::3309 8999
2016-09-18T00:34:05+02:00 - info: Peer BASIC_MERKLED_API duniter.youpeek.net 8999
2016-09-18T00:34:05+02:00 - info: Peer BASIC_MERKLED_API duniter.help-web-low.fr 151.80.40.148 8999
2016-09-18T00:34:06+02:00 - info: ETIMEDOUT
2016-09-18T00:34:06+02:00 - error: Error: ETIMEDOUT
    at Timeout._onTimeout (/home/moul/projects/duniter_build/sources/node_modules/vucoin/node_modules/request/request.js:761:15)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
2016-09-18T00:34:06+02:00 - warn: ETIMEDOUT
2016-09-18T00:34:06+02:00 - info: External access: 78.227.107.45:24723
2016-09-18T00:34:06+02:00 - debug: Generating server's peering entry based on block#0...
2016-09-18T00:34:06+02:00 - debug: --> new Peer to be sent to 0 peer(s)
2016-09-18T00:34:06+02:00 - info: POST Peer J78bPUvLjx#0
```

**Comment by M5oul** [comment]
Ok, yesterday, there must be an issue somewhere.
Today, everything works fine!
I let open in case it happen again.

**Comment by c-geek** [comment]
Did you use the ARM build? Because it takes time to be generated so, maybe, you were using the old version.

**Comment by M5oul** [comment]
I used a build from source on my desktop computer and `tar.gz` build.
I didn't used ARM to try sync.
There might had some troubles on my network, like some packets losses.
