### ISSUE TITLE
After resync from a turned off node, the node do not compute blocks

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#609]
After resync from a turned off node, the node do not compute blocks:
```fish
2016-09-23T11:19:41+02:00 - info: Block #41083 added to the blockchain in 381 ms
2016-09-23T11:19:41+02:00 - info: POST Block block#41083
2016-09-23T11:19:41+02:00 - info: Block #41084 added to the blockchain in 293 ms
2016-09-23T11:19:42+02:00 - info: POST Block block#41084
2016-09-23T11:19:42+02:00 - info: Block #41085 added to the blockchain in 378 ms
2016-09-23T11:19:42+02:00 - info: POST Block block#41085
2016-09-23T11:19:42+02:00 - info: Block #41086 added to the blockchain in 339 ms
2016-09-23T11:19:42+02:00 - info: POST Block block#41086
2016-09-23T11:19:47+02:00 - info: Will pull blocks from the network in 10 min 0 sec
2016-09-23T11:19:47+02:00 - info: Duniter server listening on http://192.168.1.21:24723
2016-09-23T11:19:47+02:00 - warn: Could NOT listen to http://fe80::10ef:2572:d9a7:ffdd:24723
2016-09-23T11:19:48+02:00 - warn:  Error: listen EINVAL fe80::10ef:2572:d9a7:ffdd:24723
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1237:19)
    at listen (net.js:1286:10)
    at net.js:1395:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
2016-09-23T11:19:48+02:00 - info: >> Server ready!
```

After restarting it, node compute blocks again.

**Comment by c-geek** [comment]
I also noted there is *sometimes* an issue with proof-of-work when I restart my node after an update. But if I restart again, the proof of work starts correctly.

**Comment by c-geek** [comment]
If you are right, I will be very grateful for your analysis. This one has a very hard cause to understand!

**Comment by M5oul** [comment]
I have absolutely no idea. It still happen currently.
