### ISSUE TITLE
Daemon stopped because of PoW issue

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#613]
My ARM node daemon was no more running.
I noticed that three hours later because it wasn't answering requests.
```bash
2016-09-24T09:05:28+02:00 - info: 163.172.176.32 - GET /blockchain/blocks/50/41336 HTTP/1.1 200 2 - 14.965 ms
2016-09-24T09:05:28+02:00 - info: 163.172.130.151 - GET /blockchain/blocks/50/41336 HTTP/1.1 200 2 - 4.883 ms
2016-09-24T09:05:31+02:00 - info: 88.174.120.187 - POST /network/peering/peers HTTP/1.1 400 63 - 235.663 ms
2016-09-24T09:05:36+02:00 - error:  Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:523:16)
    at Timeout._repeat (/opt/duniter/sources/app/lib/computation/blockProver.js:279:47)
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```
Ok, I could reproduce it. Do you want database copy?

**Comment by c-geek** [comment]
Hmmm no, thanks, I think it wouldn't give me any information this time.

**Comment by c-geek** [comment]
I detected the origin, will be fixed soon.

**Comment by M5oul** [comment]
It occurs again with `0.31.0b13`:
```bash
2016-09-27T03:41:08+02:00 - error:  Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:523:16)
    at Timeout._repeat (/opt/duniter/sources/app/lib/computation/blockProver.js:289:47)
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by c-geek** [comment]
Should be better this time.
