### ISSUE TITLE
Error: All kicked members must be present under Excluded members

### ISSUE THREAD

**Issue by RavanH** [duniter/duniter#618]
After a (first) sync ended with an error from SQLite in (don't have the exact error anymore) the log says:

    ...
    2016-09-27T20:36:11+00:00 - ^[[33mwarn^[[39m: Chunk #34 is COMPLETE from 87.91.122.123:9330
    2016-09-27T20:36:11+00:00 - ^[[33mwarn^[[39m: Chunk #35 is COMPLETE from duniter.help-web-low.fr:8999
    2016-09-27T20:36:11+00:00 - ^[[33mwarn^[[39m: Chunk #36 is COMPLETE from 87.91.122.123:9330
    2016-09-27T20:36:11+00:00 - ^[[33mwarn^[[39m: Chunk #37 is COMPLETE from duniter.help-web-low.fr:8999
    2016-09-27T20:36:14+00:00 - ^[[31merror^[[39m: ERROR >> INSERT INTO idty (`revoked`,`revocation_sig`,`currentMSN`,`currentINN`,`buid`,`member`,`kick`,`$
        at Error (native)

Every attempt at syncing after this, seems to end with "Status: All kicked members must be present under Excluded members" + "All done" while the Download and Apply bars **never** say 100%

In log:

    ...
    2016-09-27T20:40:48+00:00 - ^[[33mwarn^[[39m: Chunk #15 is COMPLETE from 82.239.120.237:37968
    2016-09-27T20:40:49+00:00 - ^[[32minfo^[[39m: Block #1750 added to the blockchain in 778 ms
    2016-09-27T20:40:50+00:00 - ^[[31merror^[[39m: Error: All kicked members must be present under Excluded members
        at Error (native)
        at /opt/duniter/sources/app/lib/rules/global_rules.js:448:13
        at next (native)
        at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
        at process._tickCallback (node.js:412:9)

**Comment by c-geek** [comment]
It seems your SQLite database is somehow locked. Two possible issues:

* you have Duniter already running while using the `sync` command, you should shut it down before running `sync` by using `duniter stop`. Note how you could fix this problem definitely [by modifying the front CLI file](https://github.com/duniter/duniter/blob/dev/bin/daemon).
* maybe because you have made an `npm install` with Node v6.

In both cases, I propose you to first:

* make a `duniter stop` to stop the eventual concurrency over the SQLite database
* make `duniter reset data` to clean it up
* then `duniter sync duniter.org 8999` to try the sync again
