### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#666]
``` bash
2016-10-17T21:14:44+02:00 - error:  SyntaxError: Unexpected token <
    at Object.parse (native)
    at /opt/duniter/sources/app/lib/streams/multicaster.js:158:37
    at throw (native)
    at onRejected (/opt/duniter/sources/node_modules/co/index.js:81:24)
    at _rejected (/opt/duniter/sources/node_modules/q/q.js:844:24)
    at /opt/duniter/sources/node_modules/q/q.js:870:30
    at Promise.when (/opt/duniter/sources/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/opt/duniter/sources/node_modules/q/q.js:788:41)
    at /opt/duniter/sources/node_modules/q/q.js:604:44
    at runSingle (/opt/duniter/sources/node_modules/q/q.js:137:13)
    at flush (/opt/duniter/sources/node_modules/q/q.js:125:13)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
```

**Comment by c-geek** [comment]
OK, line 158 is:

```js
const json = JSON.parse(e.body);
```

Obviously the `e.body` starts with a `<`, probably because of an HTML answer. Maybe an Nginx or something. I should add a try/catch on this expression.
