### ISSUE TITLE
Proof-of-work with 42 leading zeros

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#687]
My node was on a fork, I manually reverted 15 blocks to make it join main fork branch:
```bash
2016-11-07T10:36:39+01:00 - info: Block #53029 added to the blockchain in 3157 ms
2016-11-07T10:36:39+01:00 - info: Stop proof-of-work worker #1
2016-11-07T10:36:39+01:00 - info: Stop proof-of-work worker #2
2016-11-07T10:36:39+01:00 - info: POST Block block#53029
2016-11-07T10:36:41+01:00 - info: Will pull blocks from the network in 4 min 0 sec
2016-11-07T10:36:41+01:00 - warn: Pulling done. Continue proof-of-work loop.
2016-11-07T10:36:41+01:00 - info: Duniter server listening on http://192.168.1.16:8999
2016-11-07T10:36:41+01:00 - error: Error on WS Server
2016-11-07T10:36:41+01:00 - error:  Error: listen EINVAL fe80::11:1ff:fec1:e6c4:8999
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at _combinedTickCallback (node.js:386:13)
    at process._tickCallback (node.js:407:11)
2016-11-07T10:36:41+01:00 - warn: Could NOT listen to http://fe80::11:1ff:fec1:e6c4:8999
2016-11-07T10:36:41+01:00 - warn:  Error: listen EINVAL fe80::11:1ff:fec1:e6c4:8999
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at _combinedTickCallback (node.js:386:13)
    at process._tickCallback (node.js:407:11)
2016-11-07T10:36:41+01:00 - info: >> Server ready!
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn: Too old membership
2016-11-07T10:36:41+01:00 - warn:  httpCode=400, ucode=2026, message=Blockstamp does not match a block
2016-11-07T10:36:42+01:00 - info: Generating proof-of-work with 42 leading zeros followed by [0-9A-B]... (CPU usage set to 30%) for block#53030 J78bPU
2016-11-07T10:36:45+01:00 - info: POST Peer TENGx7WtzF#52999
2016-11-07T10:36:57+01:00 - info: Block #53030 added to the blockchain in 3118 ms
2016-11-07T10:36:57+01:00 - info: Stop proof-of-work worker #1
2016-11-07T10:36:57+01:00 - info: Stop proof-of-work worker #2
2016-11-07T10:36:58+01:00 - info: GIVEN proof-of-work for block#53030 with 42 leading zeros followed by [0-9A-B]! stop PoW for J78bPU
2016-11-07T10:36:58+01:00 - warn: Proof-of-work computation canceled because block received
2016-11-07T10:36:58+01:00 - warn: The proof-of-work generation was canceled: Proof-of-work computation canceled because block received
2016-11-07T10:36:58+01:00 - warn: Too high difficulty: waiting for other members to write next block
2016-11-07T10:36:58+01:00 - info: POST Block block#53030
2016-11-07T10:36:58+01:00 - warn: Blockchain changed!
2016-11-07T10:36:58+01:00 - warn: Too high difficulty: waiting for other members to write next block
2016-11-07T10:37:16+01:00 - info: POST Peer 7iBkcyryui#53000
2016-11-07T10:37:17+01:00 - info: POST Peer J78bPUvLjx#53005
```

**Comment by c-geek** [comment]
I've rewritten the way proof-of-work engine dialogs with its thread. Hope it will be better this time, I close the issue for now, but do not hesitate to reopen it later on if you reproduce it.

**Comment by c-geek** [comment]
It occured again on my machine:

     info: POST Block block#68560
    info: Block #68561 added to the blockchain in 125 ms
    warn: Blockchain changed!
    debug: --> new Block to be sent to 2 peer(s)
    debug:  `--> to peer DeCipRbinE [member] (212.47.227.101:8999)
    debug:  `--> to peer M0_HnFcSms [------] (88.174.120.187:9330)
    info: POST Block block#68561
    info: Block #68562 added to the blockchain in 133 ms
    warn: Blockchain changed!
    info: Will pull blocks from the network in 4 min 0 sec
    warn: Pulling done. Continue proof-of-work loop.
    debug: --> new Block to be sent to 2 peer(s)
    debug:  `--> to peer DeCipRbinE [member] (212.47.227.101:8999)
    info: POST Block block#68562
    debug:  `--> to peer M0_HnFcSms [------] (88.174.120.187:9330)
    info: Generating proof-of-work with 38 leading zeros followed by [0-5]... (CPU usage set to 100%) for block#68563 HnFcSm

**Comment by c-geek** [comment]
I think the issue was occuring **if you use several nodes with the same key** and when a new block was received quickly after the previous one. Indeed, in such case:

1. in a first time, the permanent prover was seeing "I can make the next block"
2. forging the next block (can take several seconds)
3. --- A new block was received from a sibling node ---
4. Computing the trial

But of course, if at step 4 the received block is from a sibling node, the difficulty is immediatly raised. In this situation, the "too high difficulty" rule was circumvented.
