### ISSUE TITLE
Node crash, daemon is stopped with only IPv6 conf

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#688]
I configure my node without IP4 and domain name, only two field containing global IP6:
My node stop running, as I want to restart it, it says it's not running:
Logs are not very explicite:
```bash
2016-11-07T11:12:43+01:00 - info: >> NODE STARTING
2016-11-07T11:12:43+01:00 - info: UPnP: configuring...
2016-11-07T11:12:44+01:00 - info: Node version: 0.40.3
2016-11-07T11:12:44+01:00 - info: Node pubkey: J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
2016-11-07T11:12:44+01:00 - info: Crawling the network...
2016-11-07T11:12:44+01:00 - info: Crawling done.
2016-11-07T11:12:44+01:00 - info: Storing self peer...
2016-11-07T11:12:44+01:00 - info: Sibling endpoints: 0=BASIC_MERKLED_API misc.moul.re 78.227.107.45 8999
2016-11-07T11:12:44+01:00 - info: External access: [2a01:e34:ee36:b2d0:e79:cd45:ed65:147]:24723
2016-11-07T11:12:44+01:00 - info: Changing conf to: {"prefix":10} on engine#1
2016-11-07T11:12:44+01:00 - info: Changing conf to: {"prefix":10} on engine#2
2016-11-07T11:12:44+01:00 - info: Changing conf to: {"prefix":10} on engine#3
2016-11-07T11:12:44+01:00 - info: Changing conf to: {"prefix":10} on engine#4
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - info: Next peering signal in 10 min
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - info: Pulling blocks from the network...
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - info: POST Peer J78bPUvLjx#53015
2016-11-07T11:12:44+01:00 - warn: Too old membership
2016-11-07T11:12:44+01:00 - info: POST Peer J78bPUvLjx#53015
2016-11-07T11:12:45+01:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-3]... (CPU usage set to 40%) for block#53041 J78bPU
2016-11-07T11:12:46+01:00 - info: Will pull blocks from the network in 4 min 0 sec
```

If I only add local IP4, it doesn't crash.
May be the cause could be when connecting with my other local node which doesn't handle IP6.

**Comment by c-geek** [comment]
I've reproduced this:

    cgeek@novobuntu:~/dev/duniter$ bin/duniter webstart
    2016-11-08T15:08:17+01:00 - debug: Plugging file system...
    2016-11-08T15:08:17+01:00 - info: Duniter web admin listening on http://localhost:9220
    2016-11-08T15:08:17+01:00 - debug: Loading conf...
    2016-11-08T15:08:17+01:00 - debug: Loading crypto functions...
    2016-11-08T15:08:17+01:00 - debug: Opening SQLite database "/home/cgeek/.config/duniter/duniter_default/duniter.db"...
    2016-11-08T15:08:17+01:00 - debug: Upgrade database...
    2016-11-08T15:08:17+01:00 - info: Duniter server listening on http://null:33036
    2016-11-08T15:08:17+01:00 - error: Error on WS Server
    2016-11-08T15:08:17+01:00 - error:  Error: listen EADDRINUSE 2a01:e35:8ae7:8bb0:c00:7602:ea52:897b:33036
        at Object.exports._errnoException (util.js:1036:11)
        at exports._exceptionWithHostPort (util.js:1059:20)
        at Server._listen2 (net.js:1252:14)
        at listen (net.js:1288:10)
        at net.js:1398:9
        at _combinedTickCallback (internal/process/next_tick.js:77:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
    2016-11-08T15:08:17+01:00 - error:  Error: listen EADDRINUSE 2a01:e35:8ae7:8bb0:c00:7602:ea52:897b:33036
        at Object.exports._errnoException (util.js:1036:11)
        at exports._exceptionWithHostPort (util.js:1059:20)
        at Server._listen2 (net.js:1252:14)
        at listen (net.js:1288:10)
        at net.js:1398:9
        at _combinedTickCallback (internal/process/next_tick.js:77:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)


Because of [these lines](https://github.com/duniter/duniter/blob/c3067a1e8e99d0f724acb32885dfbd68ef61e6cb/app/lib/streams/bma.js#L11-L14), which should be wrapped by an `if (server.conf.ipv4) { ... }`.

**Comment by M5oul** [comment]
Works fine on my side.
