### ISSUE TITLE
Migration to DUP v0.5 problem?

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#698]
Just after migrate to protocol v0.5, I found that on the logs of my Duniter node v0.50:
```bash
2016-11-09T14:42:43+01:00 - info: Matched 3 zeros 0008F7F63E3858F459141B87DED4640119D7E37FBD4CBA684C3DB9F395C0FD4A with Nonce = 20100000034117 for block#53641 by J78bPU
2016-11-09T14:42:46+01:00 - info: Pulling blocks from the network...
2016-11-09T14:42:46+01:00 - warn:  Error: `Version: 4` must follow another V4 block, a V3 block or be the root block
    at Error (native)
    at /home/moul/projects/duniter/app/lib/rules/global_rules.js:28:15
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2016-11-09T14:42:46+01:00 - warn:  Error: `Version: 4` must follow another V4 block, a V3 block or be the root block
    at Error (native)
    at /home/moul/projects/duniter/app/lib/rules/global_rules.js:28:15
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2016-11-09T14:42:46+01:00 - warn:  Error: `Version: 4` must follow another V4 block, a V3 block or be the root block
    at Error (native)
    at /home/moul/projects/duniter/app/lib/rules/global_rules.js:28:15
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2016-11-09T14:42:47+01:00 - info: Will pull blocks from the network in 4 min 0 sec
2016-11-09T14:42:52+01:00 - info: Matched 3 zeros 0004F8AB5E813954C3FA89B10BF16A56C21C814F6882F2008511BB4B8107EBD1 with Nonce = 20200000029663 for block#53641 by J78bPU
```

What does it means? It is ok?

**Comment by c-geek** [comment]
It was the v0.40.x nodes which were sending V4 blocks, and the DUP 0.5 rule was triggered. It is normal.
