### ISSUE TITLE
Function don't seems to exist

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#700]
```bash
2016-11-09T16:18:11+01:00 - info: Stop proof-of-work worker #1
2016-11-09T16:18:11+01:00 - info: Stop proof-of-work worker #2
2016-11-09T16:18:11+01:00 - error: TypeError: written.json is not a function
    at /opt/duniter/sources/app/controllers/abstract.js:12:20
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:412:9)
2016-11-09T16:18:11+01:00 - warn: written.json is not a function
2016-11-09T16:18:12+01:00 - info: GIVEN proof-of-work for block#53671 with 4 leading zeros followed by [0-2]! stop PoW for J78bPU
2016-11-09T16:18:12+01:00 - warn: Proof-of-work computation canceled because block received
```

**Comment by M5oul** [comment]
Or, may be `written` doesn't have `.json()` method:
https://github.com/duniter/duniter/blob/master/app/controllers/abstract.js#L12

**Comment by c-geek** [comment]
This one needs more informations to be fixed. I've added some code to wrap this particular buggy line, which will show informations about what is the document that provoked the bug.

I put this bug at Horizon milestone.

**Comment by c-geek** [comment]
Finally catched! This is the revocation document which is producing the issue. That explains why it did not occur very often.

**Comment by c-geek** [comment]
False flag, a local modification made this bug thrown. But the origin is similar anyway, it has something to do with a returned object that does not has the `json()` method.
