### ISSUE TITLE
V5 blocks with a transaction are not immediately accepted

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#704]
<s>This issue explains a bunch of forks, because a v3 transaction is not allowed in v5 blocks. However, for a strange reason, it finally gets accepted by the nodes during a pull event. That's why, when such a wrong block is shared across the network, it is first refused, but we can see the nodes *progressively accept* the block as they pull it.

http://cgeek.fr:9330/blockchain/current

```json
{
  "version": 5,
  "nonce": 10100000005394,
  "number": 54154,
  "powMin": 78,
  "time": 1478855995,
  "medianTime": 1478854082,
  "membersCount": 184,
  "monetaryMass": 919973230203512,
  "unitbase": 6,
  "issuersCount": 15,
  "issuersFrame": 100,
  "issuersFrameVar": 0,
  "currency": "test_net",
  "issuer": "BmDsozDoF3AW5x1G296tj9Mk6pRgo7sLvmYkPWknTyNQ",
  "signature": "y90IbpqI9W15s20Sw+HymPN7jcOyVDOWORB/3pzaBoe95yhvCsMajWE7fmqnO5OZU2UPjVgTTHJXAPvL7CzTCg==",
  "hash": "00001AFB360CCE4070164FFE367EB09E691158D7B12939C6D9B9A976DB902F05",
  "parameters": "",
  "previousHash": "000008BA796276995D4A7C8DB23225781543F695EC55E903CCFC381683E96DAE",
  "previousIssuer": "5ExBCM9a9DJSxtRgjkEoNxX3LvUVEeYsG6WZAbChGfn6",
  "inner_hash": "71DBF8803A21D0D650443340D2E892B0A95D8A0F5CD369618B8EAF8059B45CC7",
  "dividend": null,
  "identities": [],
  "joiners": [],
  "actives": [],
  "leavers": [],
  "revoked": [],
  "excluded": [],
  "certifications": [],
  "transactions": [
    {
      "version": 3,
      "blockstamp": "54152-00001D923929A263A322279B6C39A97CE7F53C8C15F1039FAC32E0F8FC54A5A4",
      "locktime": 0,
      "signatories": [
        "TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS"
      ],
      "inputs": [
        "4:0:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:0",
        "7:1:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:1",
        "4:2:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:2",
        "2:3:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:3",
        "2:4:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:4",
        "2:5:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:5",
        "2846334:6:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:22"
      ],
      "unlocks": [
        "0:SIG(0)",
        "1:SIG(0)",
        "2:SIG(0)",
        "3:SIG(0)",
        "4:SIG(0)",
        "5:SIG(0)",
        "6:SIG(0)"
      ],
      "outputs": [
        "4:0:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "7:1:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "4:2:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "2:3:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "2:4:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "2:5:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "3500:6:SIG(J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3)",
        "3750:6:SIG(8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU)",
        "3500:6:SIG(7iBkcyryuikxLotKgLABb4ViWCcfZowUseG4z48ochax)",
        "3000:6:SIG(HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk)",
        "2250:6:SIG(8marFcm8bcGn3p9r4356VP8anV6UVbHVcudvW97c2a7o)",
        "6000:6:SIG(XeBpJwRLkF5J4mnwyEDriEcNB13iFpe1MAKR4mH3fzN)",
        "4250:6:SIG(BnSRjMjJ7gWy13asCRz9rQ6G5Njytdf3pvR1GMkJgtu6)",
        "2000:6:SIG(BR5DDeKff8ZoJ5NFpcP8uwXbumR6Muas3yJankpBFRem)",
        "3000:6:SIG(9bZEATXBGPUSsk8oAYi4KAChg3rHKwNt67hVdErbNGCW)",
        "500:6:SIG(DeCipRbinEwQVwvLzUwCz1MiTvmTfFmpee7xXNghh15H)",
        "500:6:SIG(92UQQCi4kdQvio4XPE5KuXRGNhUginRFz7USy9xXkpyM)",
        "250:6:SIG(BmDsozDoF3AW5x1G296tj9Mk6pRgo7sLvmYkPWknTyNQ)",
        "750:6:SIG(7WANX3x3LvaycUdkabapQGmNgGz45ndjEmJpaTjRwRyr)",
        "1500:6:SIG(2GF9YTSMdFQg44U5ngQHGrdTbEWvkTyDzQzVjh3JHKdE)",
        "2000:6:SIG(8KTEFQS78HwEz1NK627rNsYwENxNXJyvtyMAyfKPXZRB)",
        "5000:6:SIG(ATkjQPa4sn4LBF69jqEPzFtRdHYJs6MJQjvP8JdN7MtN)",
        "250:6:SIG(AVbXemA3wh38eejntFag1ePm3AfN9M5JVmPxdLJnYATj)",
        "2804334:6:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)"
      ],
      "signatures": [
        "NgOR5Sd4r9ccFyTEF8GSUaNmLnEsaji2pHrVI4J4GEOywz0+m3DrcknE0Eea36+sOEKDElERf6VCg0S9byAgAw=="
      ],
      "comment": "REMU:53596:53763",
      "currency": "test_net",
      "issuers": [
        "TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS"
      ],
      "block_number": 54154,
      "time": 1478854082,
      "blockstampTime": 0
    }
  ],
  "raw": "Version: 5\nType: Block\nCurrency: test_net\nNumber: 54154\nPoWMin: 78\nTime: 1478855995\nMedianTime: 1478854082\nUnitBase: 6\nIssuer: BmDsozDoF3AW5x1G296tj9Mk6pRgo7sLvmYkPWknTyNQ\nIssuersFrame: 100\nIssuersFrameVar: 0\nDifferentIssuersCount: 15\nPreviousHash: 000008BA796276995D4A7C8DB23225781543F695EC55E903CCFC381683E96DAE\nPreviousIssuer: 5ExBCM9a9DJSxtRgjkEoNxX3LvUVEeYsG6WZAbChGfn6\nMembersCount: 184\nIdentities:\nJoiners:\nActives:\nLeavers:\nRevoked:\nExcluded:\nCertifications:\nTransactions:\nTX:3:1:7:7:24:1:0\n54152-00001D923929A263A322279B6C39A97CE7F53C8C15F1039FAC32E0F8FC54A5A4\nTENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS\n4:0:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:0\n7:1:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:1\n4:2:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:2\n2:3:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:3\n2:4:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:4\n2:5:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:5\n2846334:6:T:7A9075CD06C32DD96877F43F2FD44E25345D21809BB0E81E9C24405A92D62D98:22\n0:SIG(0)\n1:SIG(0)\n2:SIG(0)\n3:SIG(0)\n4:SIG(0)\n5:SIG(0)\n6:SIG(0)\n4:0:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n7:1:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n4:2:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n2:3:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n2:4:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n2:5:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n3500:6:SIG(J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3)\n3750:6:SIG(8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU)\n3500:6:SIG(7iBkcyryuikxLotKgLABb4ViWCcfZowUseG4z48ochax)\n3000:6:SIG(HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk)\n2250:6:SIG(8marFcm8bcGn3p9r4356VP8anV6UVbHVcudvW97c2a7o)\n6000:6:SIG(XeBpJwRLkF5J4mnwyEDriEcNB13iFpe1MAKR4mH3fzN)\n4250:6:SIG(BnSRjMjJ7gWy13asCRz9rQ6G5Njytdf3pvR1GMkJgtu6)\n2000:6:SIG(BR5DDeKff8ZoJ5NFpcP8uwXbumR6Muas3yJankpBFRem)\n3000:6:SIG(9bZEATXBGPUSsk8oAYi4KAChg3rHKwNt67hVdErbNGCW)\n500:6:SIG(DeCipRbinEwQVwvLzUwCz1MiTvmTfFmpee7xXNghh15H)\n500:6:SIG(92UQQCi4kdQvio4XPE5KuXRGNhUginRFz7USy9xXkpyM)\n250:6:SIG(BmDsozDoF3AW5x1G296tj9Mk6pRgo7sLvmYkPWknTyNQ)\n750:6:SIG(7WANX3x3LvaycUdkabapQGmNgGz45ndjEmJpaTjRwRyr)\n1500:6:SIG(2GF9YTSMdFQg44U5ngQHGrdTbEWvkTyDzQzVjh3JHKdE)\n2000:6:SIG(8KTEFQS78HwEz1NK627rNsYwENxNXJyvtyMAyfKPXZRB)\n5000:6:SIG(ATkjQPa4sn4LBF69jqEPzFtRdHYJs6MJQjvP8JdN7MtN)\n250:6:SIG(AVbXemA3wh38eejntFag1ePm3AfN9M5JVmPxdLJnYATj)\n2804334:6:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\nREMU:53596:53763\nNgOR5Sd4r9ccFyTEF8GSUaNmLnEsaji2pHrVI4J4GEOywz0+m3DrcknE0Eea36+sOEKDElERf6VCg0S9byAgAw==\nInnerHash: 71DBF8803A21D0D650443340D2E892B0A95D8A0F5CD369618B8EAF8059B45CC7\nNonce: 10100000005394\n"
}
```

</s>

**Comment by c-geek** [comment]
Another one right now:

```json
{
  "version": 5,
  "nonce": 10100000020365,
  "number": 54156,
  "powMin": 78,
  "time": 1478856711,
  "medianTime": 1478854729,
  "membersCount": 184,
  "monetaryMass": 919973230203512,
  "unitbase": 6,
  "issuersCount": 15,
  "issuersFrame": 100,
  "issuersFrameVar": 0,
  "currency": "test_net",
  "issuer": "XeBpJwRLkF5J4mnwyEDriEcNB13iFpe1MAKR4mH3fzN",
  "signature": "b0pAnzVaB8KUfqNiOX5V4ptgRnmFEMPZ3s51j02wyJeknxvIjC0l0QqhWhyafnHA3mPoRCiznq0mOzxtTJTXBg==",
  "hash": "000005BB44F42946604209A41A40A8B4EBF22FF3D48B1E85DD5DE877D83DE575",
  "parameters": "",
  "previousHash": "000006C344BD4B3B52EC8171D2634CA2E0EB152A1708B8FD16815D6895207F66",
  "previousIssuer": "XeBpJwRLkF5J4mnwyEDriEcNB13iFpe1MAKR4mH3fzN",
  "inner_hash": "D8D8D2A5D1F59B3A53AE92E0C465F6AAFF0BDCCFB0AED4FDA28DF1DC0A9151DF",
  "dividend": null,
  "identities": [],
  "joiners": [],
  "actives": [],
  "leavers": [],
  "revoked": [],
  "excluded": [],
  "certifications": [],
  "transactions": [
    {
      "version": 3,
      "blockstamp": "54154-00001AFB360CCE4070164FFE367EB09E691158D7B12939C6D9B9A976DB902F05",
      "locktime": 0,
      "signatories": [
        "TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS"
      ],
      "inputs": [
        "4:0:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:0",
        "7:1:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:1",
        "4:2:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:2",
        "2:3:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:3",
        "2:4:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:4",
        "2:5:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:5",
        "2804334:6:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:23"
      ],
      "unlocks": [
        "0:SIG(0)",
        "1:SIG(0)",
        "2:SIG(0)",
        "3:SIG(0)",
        "4:SIG(0)",
        "5:SIG(0)",
        "6:SIG(0)"
      ],
      "outputs": [
        "4:0:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "7:1:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "4:2:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "2:3:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "2:4:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "2:5:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)",
        "3750:6:SIG(BmDsozDoF3AW5x1G296tj9Mk6pRgo7sLvmYkPWknTyNQ)",
        "7000:6:SIG(XeBpJwRLkF5J4mnwyEDriEcNB13iFpe1MAKR4mH3fzN)",
        "4000:6:SIG(8marFcm8bcGn3p9r4356VP8anV6UVbHVcudvW97c2a7o)",
        "5000:6:SIG(BnSRjMjJ7gWy13asCRz9rQ6G5Njytdf3pvR1GMkJgtu6)",
        "3000:6:SIG(7iBkcyryuikxLotKgLABb4ViWCcfZowUseG4z48ochax)",
        "250:6:SIG(AVbXemA3wh38eejntFag1ePm3AfN9M5JVmPxdLJnYATj)",
        "3500:6:SIG(HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk)",
        "2750:6:SIG(8KTEFQS78HwEz1NK627rNsYwENxNXJyvtyMAyfKPXZRB)",
        "2500:6:SIG(9bZEATXBGPUSsk8oAYi4KAChg3rHKwNt67hVdErbNGCW)",
        "2750:6:SIG(BR5DDeKff8ZoJ5NFpcP8uwXbumR6Muas3yJankpBFRem)",
        "1250:6:SIG(92UQQCi4kdQvio4XPE5KuXRGNhUginRFz7USy9xXkpyM)",
        "500:6:SIG(2GF9YTSMdFQg44U5ngQHGrdTbEWvkTyDzQzVjh3JHKdE)",
        "2750:6:SIG(8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU)",
        "1000:6:SIG(J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3)",
        "250:6:SIG(CSjgcGguFJe3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR)",
        "1750:6:SIG(ATkjQPa4sn4LBF69jqEPzFtRdHYJs6MJQjvP8JdN7MtN)",
        "2762334:6:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)"
      ],
      "signatures": [
        "pVC51nXhw4CR7kh4jTPyF9FWhK3AGTNfjsl/sFX+xC2u4u9AphNJ0oAJBfzfAbaAg5pSZel1tdYSLX3h8vH+Dg=="
      ],
      "comment": "REMU:53764:53931",
      "currency": "test_net",
      "issuers": [
        "TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS"
      ],
      "block_number": 54156,
      "time": 1478854729,
      "blockstampTime": 0
    }
  ],
  "raw": "Version: 5\nType: Block\nCurrency: test_net\nNumber: 54156\nPoWMin: 78\nTime: 1478856711\nMedianTime: 1478854729\nUnitBase: 6\nIssuer: XeBpJwRLkF5J4mnwyEDriEcNB13iFpe1MAKR4mH3fzN\nIssuersFrame: 100\nIssuersFrameVar: 0\nDifferentIssuersCount: 15\nPreviousHash: 000006C344BD4B3B52EC8171D2634CA2E0EB152A1708B8FD16815D6895207F66\nPreviousIssuer: XeBpJwRLkF5J4mnwyEDriEcNB13iFpe1MAKR4mH3fzN\nMembersCount: 184\nIdentities:\nJoiners:\nActives:\nLeavers:\nRevoked:\nExcluded:\nCertifications:\nTransactions:\nTX:3:1:7:7:23:1:0\n54154-00001AFB360CCE4070164FFE367EB09E691158D7B12939C6D9B9A976DB902F05\nTENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS\n4:0:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:0\n7:1:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:1\n4:2:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:2\n2:3:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:3\n2:4:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:4\n2:5:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:5\n2804334:6:T:D50DCF51E8C6A8F42836E3093F7C892F15852877E3B6C7126FB1BCB5082769DE:23\n0:SIG(0)\n1:SIG(0)\n2:SIG(0)\n3:SIG(0)\n4:SIG(0)\n5:SIG(0)\n6:SIG(0)\n4:0:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n7:1:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n4:2:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n2:3:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n2:4:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n2:5:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\n3750:6:SIG(BmDsozDoF3AW5x1G296tj9Mk6pRgo7sLvmYkPWknTyNQ)\n7000:6:SIG(XeBpJwRLkF5J4mnwyEDriEcNB13iFpe1MAKR4mH3fzN)\n4000:6:SIG(8marFcm8bcGn3p9r4356VP8anV6UVbHVcudvW97c2a7o)\n5000:6:SIG(BnSRjMjJ7gWy13asCRz9rQ6G5Njytdf3pvR1GMkJgtu6)\n3000:6:SIG(7iBkcyryuikxLotKgLABb4ViWCcfZowUseG4z48ochax)\n250:6:SIG(AVbXemA3wh38eejntFag1ePm3AfN9M5JVmPxdLJnYATj)\n3500:6:SIG(HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk)\n2750:6:SIG(8KTEFQS78HwEz1NK627rNsYwENxNXJyvtyMAyfKPXZRB)\n2500:6:SIG(9bZEATXBGPUSsk8oAYi4KAChg3rHKwNt67hVdErbNGCW)\n2750:6:SIG(BR5DDeKff8ZoJ5NFpcP8uwXbumR6Muas3yJankpBFRem)\n1250:6:SIG(92UQQCi4kdQvio4XPE5KuXRGNhUginRFz7USy9xXkpyM)\n500:6:SIG(2GF9YTSMdFQg44U5ngQHGrdTbEWvkTyDzQzVjh3JHKdE)\n2750:6:SIG(8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU)\n1000:6:SIG(J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3)\n250:6:SIG(CSjgcGguFJe3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR)\n1750:6:SIG(ATkjQPa4sn4LBF69jqEPzFtRdHYJs6MJQjvP8JdN7MtN)\n2762334:6:SIG(TENGx7WtzFsTXwnbrPEvb6odX2WnqYcnnrjiiLvp1mS)\nREMU:53764:53931\npVC51nXhw4CR7kh4jTPyF9FWhK3AGTNfjsl/sFX+xC2u4u9AphNJ0oAJBfzfAbaAg5pSZel1tdYSLX3h8vH+Dg==\nInnerHash: D8D8D2A5D1F59B3A53AE92E0C465F6AAFF0BDCCFB0AED4FDA28DF1DC0A9151DF\nNonce: 10100000020365\n"
}
```

Only `pafzedog` has accepted it yet:

![image](https://cloud.githubusercontent.com/assets/969136/20210502/39251d72-a7fa-11e6-832d-a78116d87115.png)

But after few minutes, some others pulled it:

![image](https://cloud.githubusercontent.com/assets/969136/20210522/52caa71a-a7fa-11e6-925b-9c0953298296.png)

...

![image](https://cloud.githubusercontent.com/assets/969136/20210542/6e11fa64-a7fa-11e6-884d-54d93ea8061d.png)

And this continues until the fork has resorbed. I know who is sending v3 transactions, it is Remuniter. But its v3 transactions should purely and simply be refused. They are not.

**Comment by c-geek** [comment]
I've just updated Remuniter to stop doing this. But the underlying problem has to be fixed. Things to check:

* why is v3 transaction is even included in a v5 block?
* why is it refused when shared
* why is it accepted when pulled
* we should not deduce the TX version from the block's version, but get the explicit one `TX:version`, which may be the core of the issue
* why is the block accepted during a `sync --cautious`? There must be an issue with the `InnerHash` of the block or with the transaction's signature, which is done with v3. There is another bug somewhere.

**Comment by c-geek** [comment]
Probably similar to #697: the pull does not check the version fields, which explains why only pulling resorbs the fork.

**Comment by c-geek** [comment]
Here the detected error:

	2016-11-14T20:14:20+01:00 - error: Error: Wrong inner hash
	    at Error (native)
	    at /home/cgeek/.duniter/app/lib/rules/local_rules.js:47:13
	    at next (native)
	    at onFulfilled (/home/cgeek/.duniter/node_modules/co/index.js:65:19)
	    at /home/cgeek/.duniter/node_modules/co/index.js:54:5
	    at co (/home/cgeek/.duniter/node_modules/co/index.js:50:10)
	    at Object.rules.FUNCTIONS.checkVersion.checkParameters.checkProofOfWork.checkInnerHash (/home/cgeek/.duniter/app/lib/rules/local_rules.js:44:30)
	    at /home/cgeek/.duniter/app/lib/rules/index.js:25:23
	    at next (native)
	    at onFulfilled (/home/cgeek/.duniter/node_modules/co/index.js:65:19)
	    at process._tickCallback (node.js:412:9)

**Comment by c-geek** [comment]
Here is the explanation: indeed, a v5 block must have a v3 transaction. All this is fine, but when a node added a v5 block containing a v3 transaction, it was modifying the transaction version to `5` *before sharing it*, which of course avoid the block to be correctly shared as other nodes see a wrong block (they say: "Wrong inner hash" because the given `InnerHash` is the one with the v3 transaction, not the v5 one).

**Comment by c-geek** [comment]
I've found other places where the version field was modified, during initial `sync` command.

Still needs to be fixed.
