### ISSUE TITLE
sqlite input/output error on ARM

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#727]
```bash
Progress:

Download: [||||||||||||||||||||] 100 %
Apply:    [|                   ] 5 %

Status: SQLITE_IOERR: disk I/O error
All done.
```

**Comment by M5oul** [comment]
```bash
2016-11-28T21:05:47+01:00 - warn: Chunk #3 is COMPLETE from 87.91.122.123:9330
2016-11-28T21:05:47+01:00 - warn: Chunk #2 is COMPLETE from 167.114.232.189:8999
2016-11-28T21:05:47+01:00 - warn: Chunk #1 is COMPLETE from 87.90.32.15:60527
2016-11-28T21:05:47+01:00 - warn: Chunk #0 is COMPLETE from 167.114.232.189:8999
2016-11-28T21:06:11+01:00 - error:  Error: Error: SQLITE_IOERR: disk I/O error
    at Error (native)
    at /opt/duniter/sources/app/cli.js:761:15
```

**Comment by M5oul** [comment]
More logs with 0.60.0:
```bash
Warning: 2016-12-11T22:18:00+01:00 - debug: Plugging file system...
Warning: 2016-12-11T22:18:01+01:00 - debug: Loading conf...
Warning: 2016-12-11T22:18:01+01:00 - debug: Loading crypto functions...
Warning: 2016-12-11T22:18:02+01:00 - debug: Opening SQLite database "/root/.config/duniter/duniter_default/duniter.db"...
Warning: 2016-12-11T22:18:02+01:00 - debug: Upgrade database...
Warning: 2016-12-11T22:18:02+01:00 - debug: Configuration saved.
Warning: 2016-12-11T22:18:02+01:00 - debug: Loading conf...
Warning: 2016-12-11T22:18:02+01:00 - debug: Loading crypto functions...
Warning: 2016-12-11T22:18:07+01:00 - debug: dl starts from 2750
Warning: 2016-12-11T22:18:22+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:22+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:22+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:22+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:22+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:22+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:22+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:22+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:22+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:37+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:37+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:37+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:37+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:18:52+01:00 - error: No answer after 15000ms, will retry download later.
Warning: 2016-12-11T22:23:48+01:00 - debug: dl starts from 3000
Warning: 2016-12-11T22:23:48+01:00 - debug: apply starts from 2750
Warning: 2016-12-11T22:23:48+01:00 - debug: Applying from 2750
Warning: 2016-12-11T22:23:48+01:00 - debug: Peer BSmbyQ is on same blockchain
Warning: 2016-12-11T22:24:57+01:00 - error: ERROR >> INSERT INTO block (`fork`,`hash`,`inner_hash`,`signature`,`currency`,`issuer`,`issuersCount`,`issuersFrame`,`issuersFrameVar`,`parameters`,`previousHash`,`previousIssuer`,`version`,`membersCount`,`monetaryMass`,`UDTime`,`medianTime`,`dividend`,`unitbase`,`time`,`powMin`,`number`,`nonce`,`transactions`,`certifications`,`identities`,`joiners`,`actives`,`leavers`,`revoked`,`excluded`,`len`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?); [false,"0007623873991C19DF18F4B2D0AF4A438E92617A52E9A1BF48A6C400904A65F7","0664374905075613CC4134605190707A441840A320996A2505AD355A206164A0","j1xV7omjOGqcdeDsbEC2Ba1QJRR4x2s4hXYQKJtXxKa7pb98suTkCWN+/zEWcydkapm8Gm5sh1QiWj6Szq8DAQ==","test_net","HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk",null,null,null,"","00046BE237B3BD749105CED3034807188FF935BAD21848A62257435B557F4592","HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk",2,10,"4300000",1462279383,1462362512,null,0,1462362775,54,2877,3284,"[]","[]","[]","[]","[]","[]","[]","[]",0] Error: SQLITE_IOERR: disk I/O error
Warning:     at Error (native)
Warning: 2016-12-11T22:24:57+01:00 - error:  Error: Error: SQLITE_IOERR: disk I/O error
Warning:     at Error (native)
Warning:     at /opt/duniter/sources/app/cli.js:761:15
Warning:     at process._tickCallback (node.js:412:9)
Warning: 2016-12-11T22:24:57+01:00 - debug: Trying to close SQLite...
Warning: 2016-12-11T22:24:57+01:00 - error:  Error: Error: SQLITE_IOERR: disk I/O error
Warning:     at Error (native)
Warning:     at /opt/duniter/sources/app/cli.js:761:15
Warning:     at process._tickCallback (node.js:412:9)
```

**Comment by c-geek** [comment]
Is your disk full?

**Comment by M5oul** [comment]
No.

**Comment by M5oul** [comment]
Ok, it seems there is issue on my SD card or the OS.
I close it as I can't reproduce it on a fresh Internet Cube.
