### ISSUE TITLE
Wizard network has a strange behaviour

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#729]
I have a strange problem with the network wizard.

First, I totally reset the data and the configuration : 

```bash
/opt/testnet/.duniter$ rm -rf ~/.config/duniter/
/opt/testnet/.duniter$ duniter wizard network
```

Then I choose my network settings : 

```bash
/opt/testnet/.duniter$ duniter wizard network
2016-11-25T18:32:37+01:00 - debug: Plugging file system...
2016-11-25T18:32:37+01:00 - debug: Loading conf...
2016-11-25T18:32:37+01:00 - debug: Loading crypto functions...
2016-11-25T18:32:37+01:00 - info: Checking UPnP features...
? IPv4 interface: lo 127.0.0.1
? IPv6 interface: None
? Port: 8999
? Remote IPv4: None
? Does this server has a DNS name? Yes
? DNS name: testnet.duniter.inso.ovh
2016-11-25T18:32:58+01:00 - debug: Configuration saved.
2016-11-25T18:32:58+01:00 - debug: Plugging file system...
2016-11-25T18:32:58+01:00 - debug: Loading conf...
2016-11-25T18:32:58+01:00 - debug: Loading crypto functions...
2016-11-25T18:32:58+01:00 - debug: Opening SQLite database "/opt/testnet/.config/duniter/duniter_default/duniter.db"...
2016-11-25T18:32:58+01:00 - debug: Upgrade database...
2016-11-25T18:32:58+01:00 - info: Checking UPnP features...
2016-11-25T18:33:00+01:00 - info: DNS: testnet.duniter.inso.ovh
2016-11-25T18:33:00+01:00 - info: Local & Remote IPv4: 127.0.0.1:80
2016-11-25T18:33:00+01:00 - info: Local & Remote IPv6: 2001:41d0:52:a00::648:80
2016-11-25T18:33:00+01:00 - debug: Configuration saved.
2016-11-25T18:33:00+01:00 - debug: Loading conf...
2016-11-25T18:33:00+01:00 - debug: Loading crypto functions...
2016-11-25T18:33:00+01:00 - debug: Trying to close SQLite...
2016-11-25T18:33:00+01:00 - info: Database closed.
```

As you can see, in `Info`, it does not show what I chose. I didn't choose ipv6, still it is present, I didn't choose a remote ipv4, still it shown. There is something weird here. 
In the `conf.json` file, I can see that the wrong settings are there.

Then, when it starts, it crashes : 

```bash
2016-11-25T18:35:26+01:00 - error: Error on WS Server
2016-11-25T18:35:26+01:00 - error:  Error: listen EACCES 127.0.0.1:80
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at _combinedTickCallback (node.js:386:13)
    at process._tickCallback (node.js:407:11)
2016-11-25T18:35:26+01:00 - error:  Error: listen EACCES 127.0.0.1:80
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at _combinedTickCallback (node.js:386:13)
```

**Comment by M5oul** [comment]
For the IPv6 (`None` -–> `2001:…`), that may be a conflict with auto-config tool.
Or may be the configuration was saved on some strange place and add again port 80.

**Comment by M5oul** [comment]
I also encounter strange autoconfig issue with [YnH package](https://github.com/duniter/duniter_ynh/blob/master/scripts/install#L66) since network `auto-config` was added on v.0.50.2.
