### ISSUE TITLE
Two identical sources for transactions

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#741]
```bash
2016-12-03T09:04:10+01:00 - warn: Identity with hash '27984D5080D76F22B1CA526A841F8B4A48BEA2E2F1F06870ABFD5D6272079454' not found
2016-12-03T09:04:12+01:00 - info: Transaction 53B35B91A9C51459FE14EE90A933C8C86085D519DC4548F8F0B5E36A95811277 added to block
2016-12-03T09:04:12+01:00 - error:  Error: It cannot exist 2 identical sources for transactions inside a given block
    at Error (native)
    at /home/moul/projects/duniter/app/lib/rules/local_rules.js:411:13
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
    at /home/moul/projects/duniter/node_modules/co/index.js:54:5
    at co (/home/moul/projects/duniter/node_modules/co/index.js:50:10)
    at Object.checkTxSources (/home/moul/projects/duniter/app/lib/rules/local_rules.js:391:30)
    at /home/moul/projects/duniter/app/lib/rules/local_rules.js:516:22
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2016-12-03T09:04:12+01:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-2]... (CPU usage set to 20%) for block#60093 J78bPU
2016-12-03T09:04:12+01:00 - info: Transaction 53B35B91A9C51459FE14EE90A933C8C8
```

**Comment by c-geek** [comment]
Should have been fixed by f00141c5d8797e15d391c8b0dad495119739f770
