### ISSUE TITLE
One test failed

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#755]
I tested with `yarn test` and I get one error:
```bash
  482 passing (3m)
  1 failing

  1) Protocol 0.5 Difficulties "before all" hook:
     StatusCodeError: 500 - "{\n  \"ucode\": 1002,\n  \"message\": \"V6 block cannot have medianTime < 1481029200\"\n}"
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)



error Command failed with exit code 1.
```

**Comment by c-geek** [comment]
Ignore it, it's a test that randomly fails ...

**Comment by c-geek** [comment]
(do not close this ticket, however :smile:)

**Comment by c-geek** [comment]
This error will be be removed in 0.90.
