### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#757]
trying to connect to my node this morning but it was crashed. Here are the last logs : 

```
2016-12-15T02:35:47+01:00 - info: POST Peer TENGx7WtzF#63260
2016-12-15T02:35:47+01:00 - warn: Could not reach localhost
2016-12-15T02:36:16+01:00 - info: POST Peer BSmbyQCeRx#63260
2016-12-15T02:36:17+01:00 - warn: Could not reach localhost
2016-12-15T02:36:21+01:00 - info: POST Peer CFxAJT7Wqg#63260
2016-12-15T02:36:21+01:00 - warn: Could not reach localhost
2016-12-15T02:36:22+01:00 - info: Proof-of-work interrupted for some unknown reason, restarting..
2016-12-15T02:36:22+01:00 - warn: Proof-of-work computation canceled
2016-12-15T02:36:22+01:00 - warn: The proof-of-work generation was canceled: Proof-of-work computation canceled
2016-12-15T02:36:23+01:00 - warn: Identity with hash 'AC5647C8B4703FB72D773244F75BEED9E47A01CA8037A8E6BBB79168FAC82A8A' not found
```

I can restart it but it cannot be joined by BMA. It is running the PoW.

Here are the logs at the restart : 

```
016-12-15T08:42:08+01:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-1]... (CPU usage set to 60%) for block#63291 8Fi1VS
2016-12-15T08:42:18+01:00 - info: Matched 3 zeros 0002817E7B94BCA82793EBCE2232E4BFADD428491A6FF5C154A3D715532FDD77 with Nonce = 10100000002144 for block#63291 by 8Fi1VS
2016-12-15T08:42:22+01:00 - info: Matched 3 zeros 0007134181857B9F108E15EC9A83ECCD04F45E2AA6A44349CA61A8116255D1C4 with Nonce = 10100000002740 for block#63291 by 8Fi1VS
2016-12-15T08:42:28+01:00 - info: Matched 3 zeros 000FA07A5E7975D93CED3435A36451B99BD5F37284D7EA5ED931C5569F024D4E with Nonce = 10100000003951 for block#63291 by 8Fi1VS
2016-12-15T08:42:36+01:00 - info: Pulling blocks from the network...
2016-12-15T08:42:38+01:00 - info: Block #63291 added to the blockchain in 354 ms
2016-12-15T08:42:38+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:38+01:00 - info: POST Block block#63291
2016-12-15T08:42:38+01:00 - info: Block #63292 added to the blockchain in 166 ms
2016-12-15T08:42:38+01:00 - warn: Waiting for the end of pulling...
2016-12-15T08:42:38+01:00 - info: POST Block block#63292
2016-12-15T08:42:38+01:00 - info: Block #63293 added to the blockchain in 132 ms
2016-12-15T08:42:38+01:00 - info: POST Block block#63293
2016-12-15T08:42:38+01:00 - info: GIVEN proof-of-work for block#63291 with 4 leading zeros followed by [0-1]! stop PoW for 8Fi1VS
2016-12-15T08:42:38+01:00 - warn: Proof-of-work computation canceled because block received
2016-12-15T08:42:38+01:00 - warn: The proof-of-work generation was canceled: Proof-of-work computation canceled because block received
2016-12-15T08:42:38+01:00 - info: Block #63294 added to the blockchain in 129 ms
2016-12-15T08:42:39+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:39+01:00 - info: POST Block block#63294
2016-12-15T08:42:39+01:00 - info: Block #63295 added to the blockchain in 156 ms
2016-12-15T08:42:39+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:39+01:00 - info: POST Block block#63295
2016-12-15T08:42:39+01:00 - info: Block #63296 added to the blockchain in 95 ms
2016-12-15T08:42:39+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:39+01:00 - info: POST Block block#63296
2016-12-15T08:42:39+01:00 - info: Block #63297 added to the blockchain in 100 ms
2016-12-15T08:42:39+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:39+01:00 - info: POST Block block#63297
2016-12-15T08:42:39+01:00 - info: Block #63298 added to the blockchain in 77 ms
2016-12-15T08:42:39+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:40+01:00 - info: POST Block block#63298
2016-12-15T08:42:40+01:00 - info: Block #63299 added to the blockchain in 219 ms
2016-12-15T08:42:40+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:40+01:00 - info: POST Block block#63299
2016-12-15T08:42:40+01:00 - info: Block #63300 added to the blockchain in 76 ms
2016-12-15T08:42:40+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:40+01:00 - info: POST Block block#63300
2016-12-15T08:42:40+01:00 - info: Block #63301 added to the blockchain in 36 ms
2016-12-15T08:42:40+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:40+01:00 - info: POST Block block#63301
2016-12-15T08:42:40+01:00 - info: Block #63302 added to the blockchain in 92 ms
2016-12-15T08:42:40+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:40+01:00 - info: POST Block block#63302
2016-12-15T08:42:40+01:00 - info: Block #63303 added to the blockchain in 92 ms
2016-12-15T08:42:40+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:40+01:00 - info: POST Block block#63303
2016-12-15T08:42:41+01:00 - info: Block #63304 added to the blockchain in 100 ms
2016-12-15T08:42:41+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:41+01:00 - info: POST Block block#63304
2016-12-15T08:42:41+01:00 - info: Block #63305 added to the blockchain in 72 ms
2016-12-15T08:42:41+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:41+01:00 - info: POST Block block#63305
2016-12-15T08:42:41+01:00 - info: Block #63306 added to the blockchain in 86 ms
2016-12-15T08:42:41+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:41+01:00 - info: POST Block block#63306
2016-12-15T08:42:41+01:00 - info: Block #63307 added to the blockchain in 66 ms
2016-12-15T08:42:41+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:41+01:00 - info: POST Block block#63307
2016-12-15T08:42:41+01:00 - info: Block #63308 added to the blockchain in 120 ms
2016-12-15T08:42:41+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:41+01:00 - info: POST Block block#63308
2016-12-15T08:42:41+01:00 - info: Block #63309 added to the blockchain in 79 ms
2016-12-15T08:42:41+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:41+01:00 - info: POST Block block#63309
2016-12-15T08:42:41+01:00 - info: Block #63310 added to the blockchain in 83 ms
2016-12-15T08:42:42+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:42+01:00 - info: POST Block block#63310
2016-12-15T08:42:42+01:00 - info: Block #63311 added to the blockchain in 77 ms
2016-12-15T08:42:42+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:42+01:00 - info: POST Block block#63311
2016-12-15T08:42:42+01:00 - info: Block #63312 added to the blockchain in 53 ms
2016-12-15T08:42:42+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:42+01:00 - info: POST Block block#63312
2016-12-15T08:42:42+01:00 - info: Block #63313 added to the blockchain in 67 ms
2016-12-15T08:42:42+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:42+01:00 - info: POST Block block#63313
2016-12-15T08:42:42+01:00 - info: Block #63314 added to the blockchain in 96 ms
2016-12-15T08:42:42+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:42+01:00 - info: POST Block block#63314
2016-12-15T08:42:42+01:00 - info: Block #63315 added to the blockchain in 83 ms
2016-12-15T08:42:42+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:42+01:00 - info: POST Block block#63315
2016-12-15T08:42:42+01:00 - info: Block #63316 added to the blockchain in 96 ms
2016-12-15T08:42:42+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:43+01:00 - info: POST Block block#63316
2016-12-15T08:42:43+01:00 - info: Block #63317 added to the blockchain in 149 ms
2016-12-15T08:42:43+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:43+01:00 - info: POST Block block#63317
2016-12-15T08:42:43+01:00 - info: Block #63318 added to the blockchain in 64 ms
2016-12-15T08:42:43+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:43+01:00 - info: POST Block block#63318
2016-12-15T08:42:43+01:00 - info: Block #63319 added to the blockchain in 112 ms
2016-12-15T08:42:43+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:43+01:00 - info: POST Block block#63319
2016-12-15T08:42:43+01:00 - info: Block #63320 added to the blockchain in 100 ms
2016-12-15T08:42:43+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:43+01:00 - info: POST Block block#63320
2016-12-15T08:42:43+01:00 - info: Block #63321 added to the blockchain in 143 ms
2016-12-15T08:42:43+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:44+01:00 - info: POST Block block#63321
2016-12-15T08:42:44+01:00 - info: Block #63322 added to the blockchain in 103 ms
2016-12-15T08:42:44+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:44+01:00 - info: POST Block block#63322
2016-12-15T08:42:44+01:00 - info: Block #63323 added to the blockchain in 109 ms
2016-12-15T08:42:44+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:44+01:00 - info: POST Block block#63323
2016-12-15T08:42:44+01:00 - info: Block #63324 added to the blockchain in 129 ms
2016-12-15T08:42:44+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:44+01:00 - info: POST Block block#63324
2016-12-15T08:42:44+01:00 - info: Block #63325 added to the blockchain in 281 ms
2016-12-15T08:42:44+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:44+01:00 - info: POST Block block#63325
2016-12-15T08:42:45+01:00 - info: Block #63326 added to the blockchain in 155 ms
2016-12-15T08:42:45+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:45+01:00 - info: POST Block block#63326
2016-12-15T08:42:45+01:00 - info: Block #63327 added to the blockchain in 139 ms
2016-12-15T08:42:45+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:45+01:00 - info: POST Block block#63327
2016-12-15T08:42:45+01:00 - info: Block #63328 added to the blockchain in 93 ms
2016-12-15T08:42:45+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:45+01:00 - info: POST Block block#63328
2016-12-15T08:42:45+01:00 - info: Block #63329 added to the blockchain in 73 ms
2016-12-15T08:42:45+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:45+01:00 - info: POST Block block#63329
2016-12-15T08:42:45+01:00 - info: Block #63330 added to the blockchain in 153 ms
2016-12-15T08:42:45+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:45+01:00 - info: POST Block block#63330
2016-12-15T08:42:46+01:00 - info: Block #63331 added to the blockchain in 147 ms
2016-12-15T08:42:46+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:46+01:00 - info: POST Block block#63331
2016-12-15T08:42:46+01:00 - info: Block #63332 added to the blockchain in 118 ms
2016-12-15T08:42:46+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:46+01:00 - info: POST Block block#63332
2016-12-15T08:42:46+01:00 - info: Block #63333 added to the blockchain in 72 ms
2016-12-15T08:42:46+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:46+01:00 - info: POST Block block#63333
2016-12-15T08:42:46+01:00 - info: Block #63334 added to the blockchain in 84 ms
2016-12-15T08:42:46+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:46+01:00 - info: POST Block block#63334
2016-12-15T08:42:46+01:00 - info: Block #63335 added to the blockchain in 113 ms
2016-12-15T08:42:46+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:46+01:00 - info: POST Block block#63335
2016-12-15T08:42:46+01:00 - info: Block #63336 added to the blockchain in 67 ms
2016-12-15T08:42:46+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:47+01:00 - info: POST Block block#63336
2016-12-15T08:42:47+01:00 - info: Block #63337 added to the blockchain in 103 ms
2016-12-15T08:42:47+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:47+01:00 - info: POST Block block#63337
2016-12-15T08:42:47+01:00 - info: Block #63338 added to the blockchain in 95 ms
2016-12-15T08:42:47+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:47+01:00 - info: POST Block block#63338
2016-12-15T08:42:47+01:00 - info: Block #63339 added to the blockchain in 86 ms
2016-12-15T08:42:47+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:47+01:00 - info: POST Block block#63339
2016-12-15T08:42:47+01:00 - info: Block #63340 added to the blockchain in 105 ms
2016-12-15T08:42:47+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:47+01:00 - info: POST Block block#63340
2016-12-15T08:42:47+01:00 - info: Block #63341 added to the blockchain in 90 ms
2016-12-15T08:42:47+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:47+01:00 - info: POST Block block#63341
2016-12-15T08:42:47+01:00 - info: Block #63342 added to the blockchain in 73 ms
2016-12-15T08:42:47+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:47+01:00 - info: POST Block block#63342
2016-12-15T08:42:48+01:00 - info: Block #63343 added to the blockchain in 85 ms
2016-12-15T08:42:48+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:48+01:00 - info: POST Block block#63343
2016-12-15T08:42:48+01:00 - info: Block #63344 added to the blockchain in 83 ms
2016-12-15T08:42:48+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:48+01:00 - info: POST Block block#63344
2016-12-15T08:42:48+01:00 - info: Block #63345 added to the blockchain in 87 ms
2016-12-15T08:42:48+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:48+01:00 - info: POST Block block#63345
2016-12-15T08:42:48+01:00 - info: Block #63346 added to the blockchain in 84 ms
2016-12-15T08:42:48+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:48+01:00 - info: POST Block block#63346
2016-12-15T08:42:48+01:00 - info: Block #63347 added to the blockchain in 137 ms
2016-12-15T08:42:48+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:48+01:00 - info: POST Block block#63347
2016-12-15T08:42:48+01:00 - info: Block #63348 added to the blockchain in 76 ms
2016-12-15T08:42:48+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:49+01:00 - info: POST Block block#63348
2016-12-15T08:42:49+01:00 - info: Block #63349 added to the blockchain in 102 ms
2016-12-15T08:42:49+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:49+01:00 - info: POST Block block#63349
2016-12-15T08:42:49+01:00 - info: Block #63350 added to the blockchain in 110 ms
2016-12-15T08:42:49+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:49+01:00 - info: POST Block block#63350
2016-12-15T08:42:49+01:00 - info: Block #63351 added to the blockchain in 107 ms
2016-12-15T08:42:49+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:49+01:00 - info: POST Block block#63351
2016-12-15T08:42:49+01:00 - info: Block #63352 added to the blockchain in 85 ms
2016-12-15T08:42:49+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:49+01:00 - info: POST Block block#63352
2016-12-15T08:42:49+01:00 - info: Block #63353 added to the blockchain in 74 ms
2016-12-15T08:42:49+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:49+01:00 - info: POST Block block#63353
2016-12-15T08:42:49+01:00 - info: Block #63354 added to the blockchain in 78 ms
2016-12-15T08:42:49+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:50+01:00 - info: POST Block block#63354
2016-12-15T08:42:50+01:00 - info: Block #63355 added to the blockchain in 86 ms
2016-12-15T08:42:50+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:50+01:00 - info: POST Block block#63355
2016-12-15T08:42:50+01:00 - info: Block #63356 added to the blockchain in 90 ms
2016-12-15T08:42:50+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:50+01:00 - info: POST Block block#63356
2016-12-15T08:42:50+01:00 - info: Block #63357 added to the blockchain in 82 ms
2016-12-15T08:42:50+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:50+01:00 - info: POST Block block#63357
2016-12-15T08:42:50+01:00 - info: Block #63358 added to the blockchain in 69 ms
2016-12-15T08:42:50+01:00 - info: Stop proof-of-work worker #1
2016-12-15T08:42:50+01:00 - info: POST Block block#63358
2016-12-15T08:42:50+01:00 - warn:  Error: getaddrinfo ENOTFOUND 2a01 2a01:62848
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
2016-12-15T08:42:50+01:00 - info: Peer 92UQQCi4kdQvio4XPE5KuXRGNhUginRFz7USy9xXkpyM unreachable: now considered as DOWN.
2016-12-15T08:42:50+01:00 - info: Will pull blocks from the network in 4 min 0 sec
2016-12-15T08:42:50+01:00 - warn: Pulling done. Continue proof-of-work loop.
2016-12-15T08:42:50+01:00 - info: Duniter server listening on http://127.0.0.1:8999
2016-12-15T08:42:50+01:00 - info: >> Server ready!
2016-12-15T08:42:51+01:00 - warn: Identity with hash 'AC5647C8B4703FB72D773244F75BEED9E47A01CA8037A8E6BBB79168FAC82A8A' not found
2016-12-15T08:42:53+01:00 - info: Transaction 87D65443BEE1EF548F5C302DDB8E0AAE30C608C4E0CC2BA880491EA0687C267A added to block
2016-12-15T08:42:53+01:00 - error:  Error: It cannot exist 2 identical sources for transactions inside a given block
    at Error (native)
    at /opt/testnet/.duniter/app/lib/rules/local_rules.js:415:13
    at next (native)
    at onFulfilled (/opt/testnet/.duniter/node_modules/co/index.js:65:19)
    at /opt/testnet/.duniter/node_modules/co/index.js:54:5
    at co (/opt/testnet/.duniter/node_modules/co/index.js:50:10)
    at Object.rules.FUNCTIONS.checkVersion.checkParameters.checkProofOfWork.checkInnerHash.checkPreviousHash.checkPreviousIssuer.checkUnitBase.checkBlockSignature.checkBlockTimes.checkIdentitiesSignature.checkIdentitiesUserIDConflict.checkIdentitiesPubkeyConflict.checkIdentitiesMatchJoin.checkRevokedAreExcluded.checkRevokedUnicity.checkRevokedNotInMemberships.checkMembershipsSignature.checkPubkeyUnicity.checkCertificationOneByIssuer.checkCertificationUnicity.checkCertificationIsntForLeaverOrExcluded.checkTxVersion.checkTxLen.checkTxIssuers.checkTxSources (/opt/testnet/.duniter/app/lib/rules/local_rules.js:395:30)
    at /opt/testnet/.duniter/app/lib/rules/local_rules.js:520:22
    at next (native)
    at onFulfilled (/opt/testnet/.duniter/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:412:9)
2016-12-15T08:42:53+01:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-3]... (CPU usage set to 60%) for block#63359 8Fi1VS
2016-12-15T08:43:12+01:00 - info: Matched 3 zeros 0009DE0DB082256A315B5E51F1757DB0961DB7A830EE8D94DB101287745DB5C7 with Nonce = 10100000003686 for block#63359 by 8Fi1VS
```

I had to run `duniter wizard network` again to make it run. I didn't loose any custom endpoint (BMAS).

**Comment by c-geek** [comment]
Is your node using IPv6 only?

**Comment by c-geek** [comment]
We lack informations about this issue. I close it, but feel free to reopen it (you insoleet or anyone else) if you get more informations.
