### ISSUE TITLE
Error "TypeError: Cannot read property '$null' of null" (on AbstractSQLite.js)

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#760]
J'essai denvoyer une toute petite transaction, en base 2, sur TestNet.

J'obtiens l'erreur suivante : 
```
2016-12-16T09:59:22+01:00 - debug: Document write error:  TypeError: Cannot read property '$null' of null
    at forEach (/home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/AbstractSQLite.js:240:17)
    at Array.forEach (native)
    at toParams (/home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/AbstractSQLite.js:239:29)
    at /home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/AbstractSQLite.js:141:20
    at next (native)
    at onFulfilled (/home/blavenie/git/blavenie/duniter/node_modules/co/index.js:65:19)
    at /home/blavenie/git/blavenie/duniter/node_modules/co/index.js:54:5
    at co (/home/blavenie/git/blavenie/duniter/node_modules/co/index.js:50:10)
    at SourcesDAL.AbstractSQLite.getEntity (/home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/AbstractSQLite.js:139:32)
    at SourcesDAL.AbstractSQLite.sqlExisting (/home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/AbstractSQLite.js:91:39)
    at SourcesDAL.getSource (/home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/SourcesDAL.js:76:50)
    at /home/blavenie/git/blavenie/duniter/app/lib/dal/fileDAL.js:406:37
    at next (native)
    at onFulfilled (/home/blavenie/git/blavenie/duniter/node_modules/co/index.js:65:19)
2016-12-16T09:59:22+01:00 - error: TypeError: Cannot read property '$null' of null
    at forEach (/home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/AbstractSQLite.js:240:17)
    at Array.forEach (native)
    at toParams (/home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/AbstractSQLite.js:239:29)
    at /home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/AbstractSQLite.js:141:20
    at next (native)
    at onFulfilled (/home/blavenie/git/blavenie/duniter/node_modules/co/index.js:65:19)
    at /home/blavenie/git/blavenie/duniter/node_modules/co/index.js:54:5
    at co (/home/blavenie/git/blavenie/duniter/node_modules/co/index.js:50:10)
    at SourcesDAL.AbstractSQLite.getEntity (/home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/AbstractSQLite.js:139:32)
    at SourcesDAL.AbstractSQLite.sqlExisting (/home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/AbstractSQLite.js:91:39)
    at SourcesDAL.getSource (/home/blavenie/git/blavenie/duniter/app/lib/dal/sqliteDAL/SourcesDAL.js:76:50)
    at /home/blavenie/git/blavenie/duniter/app/lib/dal/fileDAL.js:406:37
    at next (native)
    at onFulfilled (/home/blavenie/git/blavenie/duniter/node_modules/co/index.js:65:19)
```

La TX envoyée semble correcte : 

```
Version: 3
Type: Transaction
Currency: test_net
Blockstamp: 63658-0000077EEDE83BD13C4F5DF4D5C5A2D80E74039A7B8C1FFE67EAE41B49802730
Locktime: 0
Issuers:
G2CBgZBPLe6FSFUgpx2Jf1Aqsgta6iib3vmDRA1yLiqU
Inputs:
8:2:T:9C240F0C47859F5DC9D06B212A4560ECEF6AC908930F673C26AC95CFA4270900:5
7:1:T:00A01D8930E8F697100DF34784279FA9B94CCC4FF3E086833450A5884817DAF1:2
Unlocks:
0:SIG(0)
1:SIG(0)
Outputs:
8:2:SIG(5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of)
7:1:SIG(5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of)
Comment: 
```

**Comment by c-geek** [comment]
C'est bizarre oui, il faudrait lancer un nœud en mode debug (dans Webstorm par ex.) puis mettre des points d'arrêt sur les points qui posent problème (je pense à SourcesDAL.js:76) et balancer normalement la transaction, car visiblement l'identifiant ou l'index d'une des sources est renseigné à vide.

Le must du must, c'est de faire cela dans un test automatisé, qui est donc facilement reproductible dans Webstorm et nous assure une correction pérenne du bug. Mimer le code des fichiers `v0.5-transactions.js` et `tx_format.js` serait un bon moyen de le faire : 

A récupérer de `tx_format.js` : la transaction à insérer au format raw, et le bout de code `parser.syncWrite(raw)` qui renvoie un objet transaction au format JSON à partir du raw.

A récupérer de `v0.5-transactions.js` : tout le fichier qui sert de structure générale au test en instanciant un serveur, mais en remplaçant `yield cat.sendP(51, tac);` par l'envoi de la transaction fautive, par exemple avec : 

    const transactionJSON = parser.syncWrite(raw);
    const resultat = yield s1.submit(transactionJSON);

**Comment by blavenie** [comment]
ok je fais ca !

**Comment by c-geek** [comment]
Attention il y a du challenge, là tu rentres dans le dur !
