### ISSUE TITLE
duniter wizard failed after DNS name  (0.90.0)

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#791]
On a fresh install (Duniter v0.90.0), the command `duniter wizard` failed:

```
(...)
? Remote port: 10900
? Does this server has a DNS name? Yes
? DNS name: gtest.duniter.fr
2017-01-23T11:22:23+01:00 - error: Unhandled rejection: Error: Callback was already called.
2017-01-23T11:22:23+01:00 - error:  Error: Callback was already called.
    at /opt/duniter/sources/node_modules/duniter-bma/node_modules/async/dist/async.js:837:32
    at /opt/duniter/sources/node_modules/duniter-bma/index.js:258:7
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by c-geek** [comment]
Are you using the .deb package?

**Comment by c-geek** [comment]
OK, reproduced.
