### ISSUE TITLE
error Error: timeout

### ISSUE THREAD

**Issue by vincentux** [duniter/duniter#803]
Voici les logs de mon nœud Duniter 0.90.2 (as-tu besoin de plus d'infos ?)

```
2017-01-24T20:05:05+00:00 info Pulling blocks from the network...
2017-01-24T20:05:06+00:00 info Will pull blocks from the network in 0 min 20 sec
2017-01-24T20:05:09+00:00 info Checking UPnP features...
2017-01-24T20:05:11+00:00 error Error: timeout
    at Timeout._onTimeout (/opt/duniter/sources/node_modules/nnupnp/lib/nat-upnp/client.js:178:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2017-01-24T20:05:20+00:00 info Matched 3 zeros 000A10B8F4CDA40B4F67EA2F7A0785812B8A58BE1946322C2191642D29C5E125 with Nonce = 10200000004222 for block#429 by CFP3oa
2017-01-24T20:05:25+00:00 info Pulling blocks from the network...
2017-01-24T20:05:27+00:00 info Will pull blocks from the network in 0 min 20 sec
2017-01-24T20:05:31+00:00 info Matched 3 zeros 0005BA95D0E3F7AF2D57F9B69787DC81EE437B7C757AC431C8A5D3C64DAFC32D with Nonce = 10100000005224 for block#429 by CFP3oa
2017-01-24T20:05:45+00:00 info Pulling blocks from the network...
2017-01-24T20:05:46+00:00 info Will pull blocks from the network in 0 min 20 sec
2017-01-24T20:05:05+00:00 info Pulling blocks from the network...
2017-01-24T20:05:06+00:00 info Will pull blocks from the network in 0 min 20 sec
2017-01-24T20:05:09+00:00 info Checking UPnP features...
2017-01-24T20:05:11+00:00 error Error: timeout
    at Timeout._onTimeout (/opt/duniter/sources/node_modules/nnupnp/lib/nat-upnp/client.js:178:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2017-01-24T20:05:20+00:00 info Matched 3 zeros 000A10B8F4CDA40B4F67EA2F7A0785812B8A58BE1946322C2191642D29C5E125 with Nonce = 10200000004222 for block#429 by CFP3oa
2017-01-24T20:05:25+00:00 info Pulling blocks from the network...
2017-01-24T20:05:27+00:00 info Will pull blocks from the network in 0 min 20 sec
2017-01-24T20:05:31+00:00 info Matched 3 zeros 0005BA95D0E3F7AF2D57F9B69787DC81EE437B7C757AC431C8A5D3C64DAFC32D with Nonce = 10100000005224 for block#429 by CFP3oa
2017-01-24T20:05:45+00:00 info Pulling blocks from the network...
```

**Comment by c-geek** [comment]
Hmmm j'ai dû activer l'UPnP par défaut, tu peux faire disparaître l'erreur avec `duniter config --noupnp`.

**Comment by vincentux** [comment]
Pourtant la case "Use UPnP" dans l'UI est bien décoché par défaut 
et dans le fichier de config "/root/.config/duniter/duniter_default/conf.json" l'option UPnP est bien à "False".

**Comment by c-geek** [comment]
Ah oui, en regardant mieux les logs : il essaye simplement se savoir si l'UPnP est disponible. Je vais regarder tout cela de plus prêt.

En tous les cas, ça n'empêche pas ton nœud de fonctionner :-)
