### ISSUE TITLE
Sync and db issue with ARM build

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#805]
With duniter 0.90.1:
```bash
Progress:

Download: [||||||||||||||||||||] 100 %
Apply:    [|||||||||||||||||   ] 87 %

Status: SQL error "SQLITE_IOERR: disk I/O error" on query "DELETE FROM s_index WHERE identifier like '5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of' AND pos = 307;
DELETE FROM s_index WHERE identifier like 'HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk' AND pos = 307;
DELETE FROM s_index WHERE identifier like 'DC75AF3789E62457E03D7E6B906D3FA384A6D693EA094722745C2891596B0B4B' AND pos = 0;
DELETE FROM s_index WHERE identifier like 'CFP3oacjwDJARL89D2Gkz6LeMoVAu4ggE65CvqSp9Q9K' AND pos = 307;
DELETE FROM s_index WHERE identifier like 'B6E3822B5749CBCDB10AD1662DC908074527D2A9C6A2A43AEAEDDCB2ABD1F20A' AND pos = 1;
DELETE FROM s_index WHERE identifier like 'DC75AF3789E62457E03D7E6B906D3FA384A6D693EA094722745C2891596B0B4B' AND pos = 1;
DELETE FROM s_index WHERE identifier like '36BFB0D7EC206D6C1CC5C124C7ECF2260ED48175DF1D10866C454C09F1861DC3' AND pos = 0;
DELETE FROM s_index WHERE identifier like '289E9F9868209FB5D48CCFE8EB6AC52AEDEFA689EB3EEC7A906D9C687FF38FEC' AND pos = 1;
DELETE FROM s_index WHERE identifier like '1BCFBFFCE09A6DBB7D76B7C97C30CCF4221B1142F038E4D820CE6AE96602F11A' AND pos = 0;
DELETE FROM s_index WHERE identifier like '8C61C877D5DACB4EA6CE41C87490FA5A1181B2FD9782E841DCC6DD11E4E24E9C' AND pos = 0;
DELETE FROM s_index WHERE identifier like '1BCFBFFCE09A6DBB7D76B7C97C30CCF4221B1142F038E4D820CE6AE96602F11A' AND pos = 1;
DELETE FROM s_index WHERE identifier like '8C61C877D5DACB4EA6CE41C87490FA5A1181B2FD9782E841DCC6DD11E4E24E9C' AND pos = 1;
DELETE FROM s_index WHERE identifier like '7tuTjCfZ7MTyVHj7GrfA8zNJ1mpWkKL9KxkoaQNpjyAe' AND pos = 307;
DELETE FROM s_index WHERE identifier like 'A76DB7FC8B6DB34350258005FC7C1CAB0BD3498102DCC950F9D12E69D35A7AE7' AND pos = 1;
DELETE FROM s_index WHERE identifier like '60FD00C07BA1E8083DE5E2752838C92C7E6AADF7720D535CE13AD694B7536AE0' AND pos = 0;
DELETE FROM s_index WHERE identifier like '60FD00C07BA1E8083DE5E2752838C92C7E6AADF7720D535CE13AD694B7536AE0' AND pos = 1;

…
```

**Comment by c-geek** [comment]
You should check your disk space.

**Comment by M5oul** [comment]
It seems there is enough memory space:
```bash
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        15G  5.4G  8.7G  39% /
devtmpfs        503M     0  503M   0% /dev
tmpfs           503M  4.0K  503M   1% /dev/shm
tmpfs           503M   52M  451M  11% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           503M     0  503M   0% /sys/fs/cgroup
```

So, I tried to resync:
```bash
duniter reset data; duniter sync duniter.org 8999
(…)
2017-01-25T09:56:32+01:00 - error:  Error: SQL error "SQLITE_IOERR: disk I/O error" on query "BEGIN;CREATE TABLE IF NOT EXISTS s_index (op VARCHAR(10) NOT NULL,tx VARCHAR(80) NULL,identifier VARCHAR(64) NOT NULL,pos INTEGER NOT NULL,created_on VARCHAR(80) NULL,written_on VARCHAR(80) NOT NULL,written_time INTEGER NOT NULL,amount INTEGER NULL,base INTEGER NULL,locktime INTEGER NULL,consumed BOOLEAN NOT NULL,conditions TEXT,PRIMARY KEY (op,identifier,pos,written_on));CREATE INDEX IF NOT EXISTS idx_sindex_identifier ON s_index (identifier);CREATE INDEX IF NOT EXISTS idx_sindex_pos ON s_index (pos);COMMIT;"
    at Error (native)
    at Database.db.exec (/opt/duniter/sources/app/lib/dal/drivers/sqlite.js:45:23)
    at Database.replacement (/opt/duniter/sources/node_modules/sqlite3/lib/trace.js:20:31)
```

**Comment by c-geek** [comment]
I don't know what to answer you. This command runs almost everywhere, on several ARM boards, and the error says you have I/O errors.

Maybe you could try to check your disk health, or follow this thread: https://github.com/pimatic/pimatic/issues/419

**Comment by M5oul** [comment]
Ok, the SD card must be tired.
I will try with an other one.

**Comment by c-geek** [comment]
I had the following error today: `Sync interrupted because the following error occured: « SQL error "SQLITE_IOERR: disk I/O error" on query "INSERT INTO s_index [...]`.

That was because another Duniter instance was already runnning. You could check this with  `ps aux | grep node`.

Linked to #727

**Comment by M5oul** [comment]
Wow,
```bash
ps aux | grep node
root      8491 49.9  8.4 169448 87012 pts/0    Sl+  14:02   0:22 /opt/duniter/sources//node/bin/node /opt/duniter/sources//bin/duniter sync duniter.org 8999
root      8568  0.0  0.0   3672   580 pts/1    S+   14:03   0:00 grep node
root     16654  0.0  2.7 103912 28700 ?        Sl    2016  95:27 /opt/duniter/sources/node/bin/node /opt/duniter/sources/app/lib/proof.js
root     17198  0.0  2.7 103292 28248 ?        Sl    2016  29:31 /opt/duniter/sources/node/bin/node /opt/duniter/sources/app/lib/proof.js
```

PoW processes running since 2016 🗡

**Comment by M5oul** [comment]
I killed this two processes.
I still crashed with same error logs.
After the sync failed, I could see this two PoW processes still running:
```bash
ps aux | grep node
root     12471 45.0  1.9  69380 20328 ?        Rl   14:10   0:00 /opt/duniter/sources/node/bin/node /opt/duniter/sources/app/lib/proof.js
root     12477  0.0  1.8  68056 19272 ?        Rl   14:10   0:00 /opt/duniter/sources/node/bin/node /opt/duniter/sources/app/lib/proof.js
root     12484  0.0  0.0   3668   532 pts/1    S+   14:10   0:00 grep node

```

**Comment by M5oul** [comment]
Ok, it seems there is issue on my SD card or the OS.
I close it as I can't reproduce it on a fresh Internet Cube.
