### ISSUE TITLE
Websocket issue

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#831]
With 0.90.5 on ARM:
```bash
2017-02-07T09:35:33+01:00 - info: POST Peer J78bPUvLjx#4153
2017-02-07T09:35:34+01:00 - info: Changing conf to: {"prefix":10} on engine#1
2017-02-07T09:35:34+01:00 - info: Changing conf to: {"prefix":10} on engine#2
2017-02-07T09:35:34+01:00 - error: error on ws mapSync: Error: not opened
    at WebSocket.send (/opt/duniter/sources/node_modules/ws/lib/WebSocket.js:219:16)
    at wssPeer.clients.forEach (/opt/duniter/sources/node_modules/duniter-bma/lib/bma.js:123:78)
    at Array.forEach (native)
    at WebSocketServer.wssPeer.broadcast (/opt/duniter/sources/node_modules/duniter-bma/lib/bma.js:123:51)
    at /opt/duniter/sources/node_modules/duniter-bma/lib/bma.js:136:21
    at Stream.write (/opt/duniter/sources/node_modules/event-stream/index.js:204:20)
    at Stream.stream.write (/opt/duniter/sources/node_modules/through/index.js:26:11)
    at Server.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Server.Readable.push (_stream_readable.js:134:10)
    at Server.streamPush (/opt/duniter/sources/server.js:84:12)
    at /opt/duniter/sources/server.js:168:16
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at _fulfilled (/opt/duniter/sources/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/opt/duniter/sources/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/opt/duniter/sources/node_modules/q/q.js:796:13)
    at /opt/duniter/sources/node_modules/q/q.js:604:44
    at runSingle (/opt/duniter/sources/node_modules/q/q.js:137:13)
    at flush (/opt/duniter/sources/node_modules/q/q.js:125:13)
2017-02-07T09:35:34+01:00 - error: error on ws mapSync: Error: not opened
    at WebSocket.send (/opt/duniter/sources/node_modules/ws/lib/WebSocket.js:219:16)
    at wssPeer.clients.forEach (/opt/duniter/sources/node_modules/duniter-bma/lib/bma.js:123:78)
    at Array.forEach (native)
    at WebSocketServer.wssPeer.broadcast (/opt/duniter/sources/node_modules/duniter-bma/lib/bma.js:123:51)
    at /opt/duniter/sources/node_modules/duniter-bma/lib/bma.js:136:21
    at Stream.write (/opt/duniter/sources/node_modules/event-stream/index.js:204:20)
    at Stream.stream.write (/opt/duniter/sources/node_modules/through/index.js:26:11)
    at Server.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Server.Readable.push (_stream_readable.js:134:10)
    at Server.streamPush (/opt/duniter/sources/server.js:84:12)
    at /opt/duniter/sources/app/service/PeeringService.js:228:12
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
2017-02-07T09:35:34+01:00 - info: Next peering signal in 10 min
2017-02-07T09:35:35+01:00 - info: POST Peer J78bPUvLjx#4153
2017-02-07T09:35:36+01:00 - info: POST Peer J78bPUvLjx#4153
```

**Comment by M5oul** [comment]
Reproduced on my desktop computer with v0.90.6.
