### ISSUE TITLE
fork, certificationstock issue

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#850]
My node can't rejoin main fork. Here is error logs:
```bash
at Error (native)
    at /home/moul/projects/duniter/app/lib/computation/blockchainContext.js:159:71
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
2017-02-26T13:18:55+01:00 - warn:  Error: ruleCertificationStock
    at Error (native)
    at /home/moul/projects/duniter/app/lib/computation/blockchainContext.js:159:71
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
2017-02-26T13:18:55+01:00 - warn:  Error: ruleCertificationStock
    at Error (native)
    at /home/moul/projects/duniter/app/lib/computation/blockchainContext.js:159:71
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
2017-02-26T13:18:55+01:00 - warn:  Error: ruleCertificationStock
    at Error (native)
    at /home/moul/projects/duniter/app/lib/computation/blockchainContext.js:159:71
    at next (native)
```

**Comment by c-geek** [comment]
Duplicate of #848
