### ISSUE TITLE
Blockchain stucked due to 'ruleMembershipDistance' error

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#858]
Even when reverting, my node get stucked at block #10019, with a `ruleMembershipDistance` error:
```bash
2017-03-01T07:16:09+01:00 - info: Block #10017 added to the blockchain in 312 ms
2017-03-01T07:16:09+01:00 - info: POST Block block#10017
2017-03-01T07:16:09+01:00 - info: Block #10018 added to the blockchain in 291 ms
2017-03-01T07:16:10+01:00 - warn:  Error: ruleMembershipDistance
    at Error (native)
    at /home/moul/projects/duniter/app/lib/computation/blockchainContext.js:179:65
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
2017-03-01T07:16:10+01:00 - info: POST Block block#10018
2017-03-01T07:16:11+01:00 - warn:  Error: ruleMembershipDistance
    at Error (native)
    at /home/moul/projects/duniter/app/lib/computation/blockchainContext.js:179:65
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
2017-03-01T07:16:11+01:00 - info: Block #10019 added to the blockchain in 247 ms
2017-03-01T07:16:12+01:00 - info: Will pull blocks from the network in 0 min 20 sec
2017-03-01T07:16:12+01:00 - warn: Pulling done. Continue proof-of-work loop.
2017-03-01T07:16:12+01:00 - info: Generating proof-of-work with 4 leading zeros followed by [0-5]... (CPU usage set to 29%) for block#10020 J78bPU
2017-03-01T07:16:12+01:00 - info: Stop proof-of-work worker #1
2017-03-01T07:16:12+01:00 - info: Stop proof-of-work worker #2
2017-03-01T07:16:12+01:00 - info: Stop proof-of-work worker #3
2017-03-01T07:16:12+01:00 - info: Stop proof-of-work worker #4
2017-03-01T07:16:12+01:00 - info: POST Block block#10019
2017-03-01T07:16:14+01:00 - info: Matched 3 zeros 00034117D20F764909BCE8319B3E9CFFEE304E33F6E02B5A3EB4E1D6602EDBF5 with Nonce = 10400000000593 for block#10020 by J78bPU
2017-03-01T07:16:19+01:00 - info: Matched 3 zeros 000E0C64661D932EB003673BC96A1003A327B7ACCA24C0BFAA3107538B3CC70E with Nonce = 10300000001020 for block#10020 by J78bPU
```

Block #10019 looks:
```json
{
  "version": 10,
  "nonce": 10200000075523,
  "number": 10019,
  "powMin": 74,
  "time": 1488325456,
  "medianTime": 1488321533,
  "membersCount": 64,
  "monetaryMass": 19913767,
  "unitbase": 1,
  "issuersCount": 12,
  "issuersFrame": 61,
  "issuersFrameVar": 0,
  "currency": "gtest",
  "issuer": "CSjgcGguFJe3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR",
  "signature": "Zyh5xdofip5Smsj9q3dpKvOr14Nyh5Qb+U7IppQuRpYIBS02rX1pVJPdNnbbe045SBe6JnacYD6Z4GnfYydNDA==",
  "hash": "00003BA7F45E497C3FB35CE6158AC8BE6D1865A29FD2674CFB8A3B1FC28808DE",
  "parameters": "",
  "previousHash": "00001A2AB65941533B2E9371D39DC7D9AD54D96E43B5AC733BCECC8E60C2F9F6",
  "previousIssuer": "BbdyLPyABYzx8Lef3oXzkoiAQ5kn3uU96ZED7Nt17gZx",
  "inner_hash": "985EC432FD4E804836906A3DCC87B7C49F658B77807EA97007A9034A47018FF5",
  "dividend": null,
  "identities": [],
  "joiners": [],
  "actives": [
    "AmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa:fLlMRJSqldzjER9Yh9nCuU0j3LRapd1dt3pJK4yZJak4ypv6k/i1t1lYgC9xXg3QT/w0Gb0JdqnNiqd8SFLmAw==:9794-0000181B2006B7287B6719A39A775D136CEA75A7CDEC3C83AF1E9A625CCB271B:703-00003DC08D73DE52ECCF2AFD1C154A4676E86B951CF0364A1D45DF10588F5867:CandideSK8"
  ],
  "leavers": [],
  "revoked": [],
  "excluded": [],
  "certifications": [],
  "transactions": [],
  "raw": "Version: 10\nType: Block\nCurrency: gtest\nNumber: 10019\nPoWMin: 74\nTime: 1488325456\nMedianTime: 1488321533\nUnitBase: 1\nIssuer: CSjgcGguFJe3ghBBjjGyNVdvC3rqtXE7rSxUaLzjxBhR\nIssuersFrame: 61\nIssuersFrameVar: 0\nDifferentIssuersCount: 12\nPreviousHash: 00001A2AB65941533B2E9371D39DC7D9AD54D96E43B5AC733BCECC8E60C2F9F6\nPreviousIssuer: BbdyLPyABYzx8Lef3oXzkoiAQ5kn3uU96ZED7Nt17gZx\nMembersCount: 64\nIdentities:\nJoiners:\nActives:\nAmDcZSEB5MCt8GyZ1VMRt1sUwRH5D7HpXx8YKhMKZ1qa:fLlMRJSqldzjER9Yh9nCuU0j3LRapd1dt3pJK4yZJak4ypv6k/i1t1lYgC9xXg3QT/w0Gb0JdqnNiqd8SFLmAw==:9794-0000181B2006B7287B6719A39A775D136CEA75A7CDEC3C83AF1E9A625CCB271B:703-00003DC08D73DE52ECCF2AFD1C154A4676E86B951CF0364A1D45DF10588F5867:CandideSK8\nLeavers:\nRevoked:\nExcluded:\nCertifications:\nTransactions:\nInnerHash: 985EC432FD4E804836906A3DCC87B7C49F658B77807EA97007A9034A47018FF5\nNonce: 10200000075523\n"
}⏎ 
```

**Comment by c-geek** [comment]
You should try v0.90.9.

**Comment by c-geek** [comment]
Reproduced with:
    
    duniter sync gtest.duniter.org 10900 10000
    duniter peer gtest.duniter.org 10900 --nocautious
    duniter start

Then Duniter pulls the blocks, and generates the error.
