### ISSUE TITLE
Bug on money gestion?

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#871]
```bash
2017-03-04T10:48:48+01:00 - info: Will pull blocks from the network in 0 min 20 sec
2017-03-04T10:48:53+01:00 - info: Transaction 2B2D20EA1D2FA145EEB597495F2A2E1028EF5A23AA2E6B4DC056A86F25C2A2BB added to block
2017-03-04T10:48:53+01:00 - error:  Error: It cannot exist 2 identical sources for transactions inside a given block
    at Error (native)
    at /opt/duniter/sources/app/lib/rules/local_rules.js:327:13
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at /opt/duniter/sources/node_modules/co/index.js:54:5
    at co (/opt/duniter/sources/node_modules/co/index.js:50:10)
    at Object.checkTxSources (/opt/duniter/sources/app/lib/rules/local_rules.js:317:30)
    at /opt/duniter/sources/app/lib/rules/local_rules.js:416:24
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2017-03-04T10:48:53+01:00 - error:  Error: It cannot exist 2 identical sources for transactions inside a given block
    at Error (native)
    at /opt/duniter/sources/app/lib/rules/local_rules.js:327:13
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at /opt/duniter/sources/node_modules/co/index.js:54:5
    at co (/opt/duniter/sources/node_modules/co/index.js:50:10)
    at Object.checkTxSources (/opt/duniter/sources/app/lib/rules/local_rules.js:317:30)
    at /opt/duniter/sources/app/lib/rules/local_rules.js:416:24
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2017-03-04T10:48:53+01:00 - error:  Error: It cannot exist 2 identical sources for transactions inside a given block
```

**Comment by c-geek** [comment]
No, it just warns that it has identical data in the sandbox and cannot include them all.

**Comment by c-geek** [comment]
You can let this ticket opened: we just need a debug or trace, here it logs as an error.
