### ISSUE TITLE
Can't build duniter with yarn

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#899]
Can't build duniter with yarn 0.21.3:
I also tried without root user.
wotb and naclb module can't be downloaded and then, build fail:
```bash
sudo yarn install
[sudo] Mot de passe de moul : 
yarn install v0.21.3
info No lockfile found.
warning duniter@1.1.0: "devDependencies" has dependency "sha1" with range "" that collides with a dependency in "dependencies" of the same name with version "1.1.1"
[1/4] Resolving packages...
warning duniter-prover > node-uuid@1.4.7: use uuid module instead
warning request > node-uuid@1.4.7: use uuid module instead
warning coveralls > request > node-uuid@1.4.7: use uuid module instead
warning mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning duniter-crawler > duniter > duniter-ui > request > tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
warning mocha > glob > graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning mocha > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning mocha-eslint > eslint > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning istanbul > fileset > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "bl@0.7.0" has unmet peer dependency "stream-browserify@*".
[4/4] Building fresh packages...
[1/7] ⠁ naclb: http GET https://nodejs.org/download/release/v6.10.0/SHASUMS256.txt
[6/7] ⠁ wotb: GET https://nodejs.org/download/release/v6.10.0/SHASUMS256.txt
[3/7] ⠁ scryptb: http 200 https://nodejs.org/download/release/v6.10.0/node-v6.10.0-headers.tar.gz
[4/7] ⠁ duniter-ui: Downloading file https://github.com/duniter/cesium/releases/download/v0.10.2/cesium-v0.10.2-web.zip...
error /home/moul/projects/duniter/node_modules/wotb: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-pre-gyp install --fallback-to-build
Directory: /home/moul/projects/duniter/node_modules/wotb
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.23
node-pre-gyp info using node@6.10.0 | linux | x64
node-pre-gyp info check checked for "/home/moul/projects/duniter/node_modules/wotb/lib/binding/Release/node-v48-linux-x64/wotb.node" (not found)
node-pre-gyp http GET https://wotb.s3-eu-central-1.amazonaws.com/v0.5.3/Release/wotb-v0.5.3-node-v48-linux-x64.tar.gz
node-pre-gyp http 403 https://wotb.s3-eu-central-1.amazonaws.com/v0.5.3/Release/wotb-v0.5.3-node-v48-linux-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://wotb.s3-eu-central-1.amazonaws.com/v0.5.3/Release/wotb-v0.5.3-node-v48-linux-x64.tar.gz (falling back to source compile with node-gyp) 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.10.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.10.0 | linux | x64
gyp info spawn /bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/moul/projects/duniter/node_modules/wotb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules.bundled/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/moul/projects/duniter/node_modules/wotb',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.10.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make : on entre dans le répertoire « /home/moul/projects/duniter/node_modules/wotb/build »
  CXX(target) Release/obj.target/wotb/wotb.o
make: g++ : commande introuvable
wotb.target.mk:101 : la recette pour la cible « Release/obj.target/wotb/wotb.o » a échouée
make : on quitte le répertoire « /home/moul/projects/duniter/node_modules/wotb/build »
make: *** [Release/obj.target/wotb/wotb.o] Erreur 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.13-201.fc25.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/moul/projects/duniter/node_modules/wotb/lib/binding/Release/node-v48-linux-x64/wotb.node" "--module_name=wotb" "--module_path=/home/moul/projects/duniter/node_modules/wotb/lib/binding/Release/node-v48-linux-x64"
gyp ERR! cwd /home/moul/projects/duniter/node_modules/wotb
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/moul/projects/duniter/node_modules/wotb/lib/binding/Release/node-v48-linux-x64/wotb.node --module_name=wotb --module_path=/home/moul/projects/duniter/node_modules/wotb/lib/binding/Release/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/moul/projects/duniter/node_modules/wotb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.9.13-201.fc25.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/home/moul/projects/duniter/node_modules/wotb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/moul/projects/duniter/node_modules/wotb
node-pre-gyp ERR! node -v v6.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.23
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/moul/projects/duniter/node_modules/wotb/lib/binding/Release/node-v48-linux-x64/wotb.node --module_name=wotb --module_path=/home/moul/projects/duniter/node_modules/wotb/lib/binding/Release/node-v48-linux-x64' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by M5oul** [comment]
Ok, I succeed installing `node-gyp` Fedora package.
