### ISSUE TITLE
Error: Cannot read property 'httpCode' of undefined

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#929]
In Version 1.1.0 (installed from server `.deb` file) on my node, i got this error : 

```js
2017-04-04T08:28:32+02:00 - info: Changing conf to: {"prefix":10} on engine#7
2017-04-04T08:28:32+02:00 - info: Changing conf to: {"prefix":10} on engine#8
2017-04-04T08:28:32+02:00 - info: Next peering signal in 10 min
2017-04-04T08:28:32+02:00 - warn: Waiting for the end of pulling...
2017-04-04T08:28:32+02:00 - info: POST Peer 38MEAZN68P#6445
2017-04-04T08:28:32+02:00 - error:  TypeError: Cannot read property 'httpCode' of undefined
    at /opt/duniter/sources/node_modules/duniter-crawler/lib/crawler.js:198:64
    at throw (native)
    at onRejected (/opt/duniter/sources/node_modules/co/index.js:81:24)

```

I will try a `reset data` + `sync`

**Comment by c-geek** [comment]
That's a bug where an `undefined` error is thrown: for example in this code:

```js
const obj = {}
throw obj.notDefinedMember
```

We have to fully check the code for throws and verify each of them *do* exist.

**Comment by c-geek** [comment]
Do you still observe this message?
