### ISSUE TITLE
Crash at launching

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#956]
After a crash of my machine, I restart duniter and the daemon stop with following logs:
```bash
2017-04-11T18:01:05+02:00 - info: SIDE Block #9464 added to the blockchain in2017-04-11T18:07:24+02:00 - info: >> Server starting...
2017-04-11T18:07:24+02:00 - info: Node version: 1.2.2
2017-04-11T18:07:24+02:00 - info: Node pubkey: GfKERHnJTYzKhKUma5h1uWhetbA8yHKymhVH2raf2aCP
2017-04-11T18:07:24+02:00 - info: Duniter server listening on http://192.168.1.21:38662
2017-04-11T18:07:24+02:00 - info: Duniter server listening on http://[2a01:e34:ee36:b2d0:1879:97c5:5f21:728b]:38662
2017-04-11T18:07:24+02:00 - info: UPnP: configuring...
2017-04-11T18:07:24+02:00 - info: Crawling the network...
2017-04-11T18:07:24+02:00 - info: Sandbox pulling started...
2017-04-11T18:07:24+02:00 - info: Pulling blocks from the network...
2017-04-11T18:07:24+02:00 - info: Crawling done.
2017-04-11T18:07:24+02:00 - info: Sibling endpoints: 0=BASIC_MERKLED_API arm.moul.re 78.227.107.45 2a01:e34:ee36:b2d0:11:1ff:fec1:e6c4 10901
2017-04-11T18:07:24+02:00 - warn: Waiting for the end of pulling...
2017-04-11T18:07:25+02:00 - info: External access: desktop.moul.re:38662
2017-04-11T18:07:25+02:00 - info: Changing conf to: {"prefix":10} on engine#1
2017-04-11T18:07:25+02:00 - info: Changing conf to: {"prefix":10} on engine#2
2017-04-11T18:07:25+02:00 - info: Changing conf to: {"prefix":10} on engine#3
2017-04-11T18:07:25+02:00 - info: Changing conf to: {"prefix":10} on engine#4
2017-04-11T18:07:25+02:00 - info: Next peering signal in 10 min
2017-04-11T18:07:25+02:00 - info: POST Peer GfKERHnJTY#9437

2017-04-11T18:07:26+02:00 - info: POST Peer GfKERHnJTY#9437
2017-04-11T18:07:26+02:00 - info: Block #9466 added to the blockchain in 1092 ms
2017-04-11T18:07:26+02:00 - info: Peer EMEH9NRYAmwDUaDtk8BCVajQ2mPEeKUwx49zwFtaiYfR unreachable: now considered as DOWN.
2017-04-11T18:07:26+02:00 - info: Peer BbdyLPyABYzx8Lef3oXzkoiAQ5kn3uU96ZED7Nt17gZx unreachable: now considered as DOWN.
2017-04-11T18:07:26+02:00 - error:  TypeError: Cannot read property 'httpCode' of undefined
    at /home/moul/projects/duniter/node_modules/duniter-crawler/lib/crawler.js:247:64
    at throw (native)
    at onRejected (/home/moul/projects/duniter/node_modules/co/index.js:81:24)
```

If I restart the deamon, it's ok, it run.

**Comment by c-geek** [comment]
Weird, I've already partially fixed the problem in #929, and duniter@1.2.2 should have this fix.

**Comment by M5oul** [comment]
I encountered it even without OS crash.
I only stopped the daemon,  restarted it later and I could reproduce it.

**Comment by c-geek** [comment]
Do you still reproduce this?

I didn't see that you said « after a crash of my machine ». That's a possible behavior: if the wotb module was working during the crash, the `wotb.bin` may be corrupted. Your node will crash every time the file is read.

The best solution is to reset + resync.

**Comment by M5oul** [comment]
Not reproduced.
I close for now.
