### ISSUE TITLE
High memory usage on ARM with 1.2.2

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#961]
```bash
2017-04-16T17:36:36+02:00 - error:  Error: spawn ENOMEM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Object.exports.fork (child_process.js:58:10)
    at /opt/duniter/sources/node_modules/duniter-prover/lib/engine.js:33:33
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at /opt/duniter/sources/node_modules/co/index.js:54:5
    at co (/opt/duniter/sources/node_modules/co/index.js:50:10)
    at restart (/opt/duniter/sources/node_modules/duniter-prover/lib/engine.js:31:25)
    at /opt/duniter/sources/node_modules/duniter-prover/lib/engine.js:59:11
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at /opt/duniter/sources/node_modules/co/index.js:54:5
    at co (/opt/duniter/sources/node_modules/co/index.js:50:10)
    at ask (/opt/duniter/sources/node_modules/duniter-prover/lib/engine.js:57:35)
    at PowEngine.status (/opt/duniter/sources/node_modules/duniter-prover/lib/engine.js:80:23)
    at Timeout.setInterval [as _onTimeout] (/opt/duniter/sources/node_modules/duniter-prover/lib/blockProver.js:219:26)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2017-04-16T17:36:36+02:00 - error: Unhandled rejection: Error: spawn ENOMEM
2017-04-16T17:36:36+02:00 - error:  Error: spawn ENOMEM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Object.exports.fork (child_process.js:58:10)
    at /opt/duniter/sources/node_modules/duniter-prover/lib/engine.js:33:33
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at /opt/duniter/sources/node_modules/co/index.js:54:5
    at co (/opt/duniter/sources/node_modules/co/index.js:50:10)
    at restart (/opt/duniter/sources/node_modules/duniter-prover/lib/engine.js:31:25)
    at /opt/duniter/sources/node_modules/duniter-prover/lib/engine.js:59:11
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
    at /opt/duniter/sources/node_modules/co/index.js:54:5
    at co (/opt/duniter/sources/node_modules/co/index.js:50:10)
    at ask (/opt/duniter/sources/node_modules/duniter-prover/lib/engine.js:57:35)
    at PowEngine.status (/opt/duniter/sources/node_modules/duniter-prover/lib/engine.js:80:23)
    at Timeout.setInterval [as _onTimeout] (/opt/duniter/sources/node_modules/duniter-prover/lib/blockProver.js:219:26)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by c-geek** [comment]
How much RAM do you have on your ARM board?

**Comment by M5oul** [comment]
1Go.

**Comment by Insoleet** [comment]
Same problem on x64 CPU. I have 2 gb of RAM.

**Comment by c-geek** [comment]
Same problem on duniter.org. Too much RAM used, which was making the server swap.

However, the process wasn't killed.

**Comment by zorun** [comment]
Could you rename this issue to something like "High RAM usage with 1.2.2" or "Memory leak in 1.2.2"?

I am having the same issue with 1.2.2 on x86_64 with the release Debian package: the amount of RAM used by duniter is growing steadily over time.  It looks like a memory leak.

I was using v1.1.0 between 17 March and 7 May (without any restart) and it was not using a lot of RAM.  Now, 24 hours after the upgrade to v1.2.2, it's already using 900 MB of RAM.

This node is only a mirror (it does not compute any block).

**Comment by sachaz** [comment]
Is this is the same issue: https://github.com/duniter/duniter/issues/910 ?

**Comment by zorun** [comment]
Good catch, I didn't see this one.

However, my node is not a member node, so the proposed fix may not work?

**Comment by c-geek** [comment]
@zorun probably that the fix won't work. I don't know yet where does the leak on mirror occurs. However the v1.2.3 will bring a memory tracer in it, so you could investigate or share memory reports.

The v1.2.3 will be released this week I hope, I'm working on it.

**Comment by c-geek** [comment]
It seems that even mirror nodes benefit from the memory fix.

If the problem is fixed on your side too, please close the issue.

**Comment by M5oul** [comment]
Seems fixed for now.
