### ISSUE TITLE
Cannot read property 'pubkey' of undefined

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#996]
```
2017-05-25T11:30:49+02:00 - warn:  TypeError: Cannot read property 'pubkey' of undefined
    at /home/cgeek/dev/duniter-ui/node_modules/duniter/app/service/BlockchainService.js:275:35
    at next (native)
    at onFulfilled (/home/cgeek/dev/duniter-ui/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by M5oul** [comment]
Each time I restart my node, the pubkey change.

**Comment by c-geek** [comment]
You should try to reinstall your modules:

    rm -rf node_modules/ yarn.lock
    yarn

**Comment by M5oul** [comment]
Yep, I did that many times but I was still reproducing this issue.

**Comment by c-geek** [comment]
Note to myself: this issue is reproduced only while developing duniter-ui.
