### ISSUE TITLE
Crash when a configured network interface is not available

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#997]
```
/home/cgeek/.nvm/versions/node/v6.10.2/bin/node --debug-brk=46835 --expose_debug_as=v8debug /home/cgeek/dev/duniter-ui/run.js direct_webstart
Debugger listening on [::]:46835
2017-05-26T10:05:13+02:00 - debug: Plugging file system...
2017-05-26T10:05:13+02:00 - debug: Loading conf...
2017-05-26T10:05:13+02:00 - debug: Configuration saved.
2017-05-26T10:05:13+02:00 - debug: Opening SQLite database "/home/cgeek/.config/duniter/duniter_default/duniter.db"...
2017-05-26T10:05:13+02:00 - debug: Upgrade database...
2017-05-26T10:05:13+02:00 - info: Web administration accessible at following address: http://localhost:9220
ddos: starting params:  { maxcount: 80,
  burst: 20,
  limit: 40,
  maxexpiry: 10,
  checkinterval: 1,
  trustProxy: true,
  includeUserAgent: true,
  whitelist: 
   [ '127.0.0.1',
     '192.168.1.24',
     '2a01:e35:8ae7:8bb0:f5f7:29ea:247c:f316',
     '2a01:e35:8ae7:8bb0:a94e:b841:a77e:c5b8' ],
  errormessage: 'Error',
  testmode: false,
  silent: false,
  silentStart: false,
  responseStatus: 429 }
2017-05-26T10:05:14+02:00 - info: Duniter server listening on http://192.168.1.24:22860
2017-05-26T10:05:14+02:00 - error: Error on WS Server
2017-05-26T10:05:14+02:00 - error:  Error: listen EADDRNOTAVAIL 2a01:e35:8ae7:8bb0:a94e:b841:a77e:c5b8:22860
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 2a01:e35:8ae7:8bb0:a94e:b841:a77e:c5b8:22860
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Process finished with exit code 1
```

**Comment by c-geek** [comment]
Only occurs in development mode of duniter-ui.
